import { readFile } from "node:fs/promises";

const requiredHtml = [
  "Post the project.",
  "Find the right crew.",
  "I need workers",
  "I need work",
  "Forge Confirmation",
  "confirmNextSteps",
  "confirmHandoff",
  "confirmFollowUp",
  "confirmCloseout",
  "Copy Handoff",
  "First-user next touch",
  "Lead Capture Setup",
  "Lead Delivery Status",
  "deliveryStatus",
  "Copy Status",
  "Backend Handoff",
  "backendHandoff",
  "Copy Backend Handoff",
  "Admin Auth Handoff",
  "authHandoff",
  "Copy Auth Handoff",
  "operatorGuardPanel",
  "Worker Leads",
  "Export Workers CSV",
  "Copy Daily Brief",
  "Activity Log",
  "First 200 launch",
  "Early user pipeline",
  "Copy Launch Invite",
  "What happens next",
  "Every early signup turns into a clear follow-up.",
  "Can people sign up?",
  "Yes: start with a controlled first-user group.",
  "Safe to collect today",
  "Copy Signup Checklist",
  "Forge Launch Status",
  "Soft launch readiness",
  "Forge is ready for controlled first-user demos, not broad public traffic yet.",
  "Soft launch decision",
  "Public launch blocker receipt",
  "publicLaunchBlockers",
  "Recommended soft-launch path",
  "Can I show someone now?",
  "No live payments",
  "Backend required",
  "Security gate required",
  "Early Access Terms & Privacy",
  "Forge is a controlled beta MVP.",
  "Terms & Privacy",
  "Forge Auto Services",
  "Forge Auto & Transport",
  "Buy. Sell. Repair. Transport.",
  "Sell My Car on Forge",
  "Forge Platinum Auto Concierge",
  "Premium vehicle sourcing, selling, consignment, and white-glove transport.",
  "vehicleListingForm",
  "vehicleSellingPath",
  "vehiclePartnerConsent",
  "Track Your Home From Dirt to Done",
  "Forge Build Tracker",
  "homebuildingFeatureGrid",
  "buildTrackerDashboard",
  "Sample data only",
  "Training & Careers",
  "Apply to trade schools, unions, and blue-collar AI jobs.",
  "opportunityForm",
  "opportunityStats",
  "opportunityTrackGrid",
  "Copy Application Plan",
  "Copy Career Leads",
  "Save Career Interest",
  "Forge Academy",
  "Blue-collar career pathways, trade-school help, apprenticeships, resumes, and local job placement powered by Admitly.",
  "forgeAcademyStudentForm",
  "academyOptionGrid",
  "careerPlusFeatureGrid",
  "Save Career Intake",
  "Employer / contractor partner",
  "academyEmployerForm",
  "School / program partner",
  "academySchoolForm",
  "Admitly Trade Pathways",
  "Your Future. Admitted.",
  "admitlyTradePathwayForm",
  "admitlyPathwayGrid",
  "admitlyDashboardGrid",
  "Save Trade Pathway Lead",
  "adminForgeAcademyTable",
  "adminTradePathwaysTable",
  "Copy Academy Queue",
  "Copy Auto Brief",
  "Dealer network",
  "Dealer setup checklist",
  "Copy Setup Checklist",
  "autoDealerSetup",
  "Copy Dealer Plan",
  "autoDealerGrid",
  "Dealer Partner",
  "Buyer inquiries",
  "autoInquiryForm",
  "autoInquiryList",
  "Copy Buyer Queue",
  "Auto safety",
  "Forge Road Rescue",
  "Emergency? Call 911 first.",
  "Pothole Impact Help",
  "roadRescueForm",
  "Road Rescue Leads",
  "Export Road Rescue CSV",
  "Report the Pothole",
  "Photography & Videography",
  "Hire a Photographer",
  "Request a Shoot",
  "Apply as a Photographer",
  "creativeLeadForm",
  "creativeProviderForm",
  "creativeDeliveryDeadline",
  "creativeProviderEditingSoftware",
  "Photography & Videography Booking Notes",
  "Built for trust and quality.",
  "Forge helps customers request local creatives, including photographers and videographers. Provider claims remain pending until reviewed.",
  "NorthStar Creative Co.",
  "Grow Your Business with North Star Creative Co.",
  "Forge helps you find work. North Star Creative Co. helps your business win more of it.",
  "Grow My Business",
  "Request a Free Marketing Audit",
  "northstarLeadForm",
  "northstarServices",
  "northstarBudget",
  "adminNorthstarTable",
  "adminNorthstarPipeline",
  "Forge Capital Desk",
  "Explore business-finance readiness without pressure.",
  "A Flex referral is not active unless every written approval and official-link gate is complete.",
  "Forge Capital Desk Lead Form",
  "Continue to approved referral",
  "flexLeadForm",
  "flexConsentToContact",
  "flexConsentReferral",
  "flexInterestedWebsiteCrm",
  "Personal Driver / Private Driver Services",
  "personalDriverRequestForm",
  "personalDriverProviderForm",
  "adminPersonalDriverRequestsTable",
  "adminPersonalDriverProvidersTable",
  "Forge Payments / Merchant Services",
  "merchantServicesLeadForm",
  "merchantServicesCompliance",
  "adminMerchantServicesTable",
  "Local Products / Makers",
  "localProductVendorForm",
  "adminLocalProductsTable",
  "Worker Trust / Proof Ledger",
  "Green/Silver/Gold",
  "providerGrowthTools",
  "adminFlexLeadsTable",
  "flex_link_sent",
  "Copy Queue",
  "Save Finance Interest",
  "Start here",
  "Choose the path that matches why you came to Forge.",
  "startPathGrid",
  "Copy First User Links",
  "Forge Building",
  "Build smarter. Fund smarter. Find the right next step.",
  "Request Contractor Finance Review",
  "buildingLeadForm",
  "adminBuildingFullTable",
  "adminBuildingFullPipeline",
  "Quick Capture",
  "Save the lead before the moment passes.",
  "Referral / Friend Leads",
  "Follow-Up Queue",
  "followUpCommandStrip",
  "Copy Command",
  "Public View",
  "Import Backup",
  "Submit a Bid",
  "Bid Activity",
  "My Job Status",
  "Status privacy",
  "No payment or account password is required.",
  "Customer status flow",
  "Lookup saved job",
  "Open John's Job Status",
  "John customer proof shortcuts",
  "data-login-thread",
  "Review bids",
  "Message Forge",
  "Choose next step",
  "Demo script",
  "Log in to Forge",
  "Mike Jones",
  "One-minute worker proof",
  "Review Jobs",
  "Join Forge as a Contractor",
  "Forge Admin",
  "Forge Messages",
  "Active conversations",
  "messageSummary",
  "messageHandoffPanel",
  "Bid-to-message flow",
  "What happens after this bid?",
  "Messages carry the handoff",
  "Open Customer Review",
  "Save as Sent",
  "Forge Reports",
  "MVP traction report",
  "Profile Status",
  "Demo proof path",
  "Copy Path",
  "profileProofPath",
  "profileReadiness",
  "profileStatusReceipt",
  "profilePerspectiveSwitch",
  "profileCommandStrip",
  "profileVisibilityPanel",
  "launchHandoffReceipt",
  "Profile command summary",
  "Profile visibility",
  "First-user handoff receipt",
  "Status brief",
  "Copy Status Brief",
  "profileBrief",
  "profileDemoHandoff",
  "Copy Handoff",
  "Status checklist",
  "Ready for bids",
  "Operator active",
  "Perspective Demo",
  "Show people their side",
  "Demo day command",
  "Start here, then capture one real next action.",
  "One-click proof",
  "Switch roles without losing the story.",
  "demoProofSwitchboard",
  "3-minute walkthrough",
  "Phone demo order",
  "Tap these four if you only have a minute.",
  "Message handoff",
  "Open Msgs",
  "Phone closeout",
  "phoneFastPass",
  "Phone demo fast pass",
  "End with one saved next action.",
  "Copy Ask",
  "Live demo cue cards",
  "demoCueGrid",
  "First-user receipt",
  "launchReceiptGrid",
  "Copy Receipt",
  "Best demo path",
  "Shareable links",
  "Copy Demo Script",
  "After the demo",
  "Turn interest into one clear next step.",
  "MVP ready today",
  "Final demo checklist",
  "Launch day command checklist",
  "Run this exact order with the first 200 people.",
  "First-user demo pack",
  "Open the right proof screen, then save the handoff.",
  "launchDemoPack",
  "launchDecisionCard",
  "launchFinalChecklist",
  "Final first-user checklist",
  "Copy Checklist",
  "launchShowPlan",
  "launchSendBoard",
  "First-user send board",
  "Choose + Message",
  "Copy Demo Pack",
  "Copy Close Ask",
  "Follow-up consent",
  "No payment is collected in this MVP.",
  "Contractor follow-up",
  "First worker path",
  "What happens after you join?",
  "workerFollowUpConsent",
  "workerTerms",
  "captureTriageBoard",
  "Quick capture triage board",
  "I agree Forge may contact me by text, phone, or email about early worker opportunities.",
  "Open demo paths",
  "Open launch status",
  "Open profile status",
  "First-user count breakdown",
  "firstUserCountBreakdown",
  "Copy Count",
  "First 200 launch queue",
  "first200QueueGrid",
  "Copy Queue",
  "Follow-up and backup audit",
  "followUpAuditGrid",
  "Copy Audit",
  "Safety Center",
  "Check the MVP before real outreach.",
  "Copy Launch Gate",
  "Public Deploy Preflight",
  "publicReadinessScore",
  "Copy RC Packet",
  "Copy Runbook",
  "Copy Check Command",
  "Copy Final Gate",
  "Copy Deploy Plan",
  "Copy Security Review",
  "deployChecklist",
  "launchGate",
  "safetyChecklist",
  "First-user closeout",
  "Finish every demo block with the same sequence.",
  "firstUserCloseout",
  "Copy Closeout",
  "Launch Command",
  "Who needs action today?",
  "launchCommandCenter",
  "Outreach Recap",
  "What moved today?",
  "outreachRecap",
  "Next 10 Batch",
  "Run one focused outreach sprint.",
  "outreachBatch",
  "Complete Sprint",
  "Session History",
  "Recent outreach sprints.",
  "sessionHistory",
  "What project do you need completed?",
  "premiumServiceGrid",
  "Browse All Services",
  "Get Quotes",
  "marketplaceCtaGrid",
  "Customer Dashboard",
  "customerDashboardSummary",
  "marketplaceDiscoverySummary",
  "adminMarketplaceControl",
  "workerMarketplaceReadiness",
  "Provider marketplace readiness",
  "Local account prototype",
  "accountSignupForm",
  "accountPrototypePanel",
  "customerProfileForm",
  "Customer Profile",
  "Labor line items",
  "Payment milestones",
  "Quote valid until",
  "admitlyPresentationBody",
  "styles.css?v=133",
  "app.js?v=133"
];

const requiredJs = [
  "forge.wireframe.mvp.v1",
  "sendLead",
  "exportCsv",
  "exportBackup",
  "copyDailyBrief",
  "foundingSegments",
  "renderFounding200",
  "copyFirst200Plan",
  "quickLeadForm",
  "referrals",
  "markReferralContacted",
  "togglePublicMode",
  "importBackup",
  "copyFollowUpQueue",
  "queue-next",
  "queue-rank",
  "followUpProgress",
  "renderFollowUpProgress",
  "todayFollowUp",
  "renderTodayFollowUp",
  "filteredFollowUpRows",
  "followUpScore",
  "followUpReason",
  "bidForm",
  "jobFlowTracker",
  "jobFlowSteps",
  "jobHandoffRail",
  "jobHandoffRailRows",
  "copyJobHandoffRail",
  "Forge job handoff rail",
  "jobFlowBrief",
  "jobFlowBriefRows",
  "copyJobFlowBrief",
  "Forge job flow brief",
  "jobDetailHandoffPanel",
  "Detail handoff",
  "Copy Detail Handoff",
  "copyDetailHandoff",
  "Forge job detail handoff",
  "Job-to-bid flow",
  "Copy Flow Brief",
  "Where this job stands now",
  "Message / schedule",
  "renderForgeAcademy",
  "renderAdmitlyTradePathways",
  "renderAdmitlyPresentation",
  "renderMarketplaceCommandCenter",
  "forgeMarketplaceJobStatuses",
  "forgeMarketplaceVerificationStates",
  "copyMarketplaceCommand",
  "copyMarketplaceJob",
  "requestProviderQuote",
  "inviteProviderToJob",
  "saveProvider",
  "forgeAccountRoles",
  "submitLocalAccountSignup",
  "submitCustomerProfile",
  "copyAuthPrototype",
  "startCompanyProfile",
  "reviseBid",
  "withdrawBid",
  "setJobLifecycleStatus",
  "Awaiting Approval",
  "Disputed",
  "submitAdmitlyStudentInterest",
  "submitAdmitlyEducatorInterest",
  "admitly-stanford",
  "customer-dashboard",
  "renderAcademyAdmin",
  "copyAcademyBrief",
  "copyAcademyAdminQueue",
  "resumeRequestFromAcademyLead",
  "resumeRequestFromTradePathwayLead",
  "academyConfirmation",
  "tradePathwayLeads",
  "forgeAcademyLeads",
  "adminBidsTable",
  "statusLookupForm",
  "renderStatusResults",
  "statusEmptyState",
  "Customer proof summary",
  "statusMessageBridge",
  "statusMessageBridgeRows",
  "copyStatusMessageBridge",
  "Status to message bridge",
  "Forge status to message bridge",
  "customerStatusDemoStrip",
  "One-minute customer proof",
  "customerStatusHandoffPanel",
  "Customer handoff",
  "Copy Status Handoff",
  "status-handoff-panel",
  "messageContextBridge",
  "messageContextBridgeRows",
  "Thread bridge",
  "message-context-bridge",
  "Launch Boundary",
  "Forge did not find a job for that contact.",
  "renderDemoSteps",
  "startPaths",
  "renderStartPaths",
  "copyFirstUserLinks",
  "Forge first-user links",
  "copySignupChecklist",
  "Forge first-user signup checklist",
  "PUBLIC_LINK_VERSION",
  "versionQuery",
  "PUBLIC_LINK_LABEL",
  "premiumServiceCategories",
  "browseAllServiceCategories",
  "renderPremiumMarketplace",
  "handlePremiumServiceSearch",
  "Become a Provider",
  "firstUserLeadCollections",
  "Vehicle seller/listing leads",
  "Auto buyer inquiries",
  "Personal driver requests",
  "Post one real job.",
  "followUpConsent",
  "Open Profile Status",
  "loginRole: \"worker\"",
  "loginScreen: \"profile\"",
  "copyInviteText",
  "vehicles",
  "autoServiceGroups",
  "autoTransportServiceCards",
  "autoLeadCategoryLabels",
  "operationsVaultDocuments",
  "autoServiceOptions",
  "autoRequests",
  "autoDealers",
  "renderAutos",
  "autoDealerName",
  "copyAutoDealerPlan",
  "copyAutoDealerSetup",
  "copyAutoDealer",
  "JoCo Auto Sales",
  "Chevelles Auto Sales",
  "Shasta Lake Auto Sales",
  "S&A Auto",
  "copyAutoServiceRequest",
  "copyAutoServiceQueue",
  "Forge Auto service request",
  "copyAutoMarketBrief",
  "copyAutoTransportMenu",
  "renderAutoAdminViews",
  "renderOperationsVault",
  "copyOperationsVaultIndex",
  "copyVehicleContact",
  "vehicleLeadTags",
  "vehicleAssignedPartner",
  "Forge Platinum Auto Concierge",
  "Marc - Portland Luxury Auto Partner",
  "autoInquiries",
  "copyAutoInquiry",
  "copyAutoInquiryQueue",
  "autoInquiryLines",
  "Forge auto buyer inquiry",
  "Forge Auto Services brief",
  "Vehicle seller lead saved.",
  "Copy Seller Info",
  "ROAD_RESCUE_SERVICE_TYPE",
  "road_rescue",
  "roadRescueRequests",
  "renderRoadRescue",
  "copyRoadRescueQueue",
  "roadRescueProviderNotification",
  "Forge Road Rescue saved your request on this device.",
  "CREATIVE_CATEGORY_VALUE",
  "CREATIVE_CATEGORY_SLUG",
  "photography_videography",
  "creativeRequestStatuses",
  "creativeProviderStatuses",
  "creativeDeliveryOptions",
  "creativeServiceTypes",
  "creativeProviderDroneCapability",
  "adminCreativeRequestsTable",
  "adminCreativeProvidersTable",
  "renderCreativePage",
  "submitCreativeLead",
  "submitCreativeProvider",
  "copyCreativeBrief",
  "copyCreativeQueue",
  "Forge creative lead",
  "Forge creative provider application",
  "NORTHSTAR_CATEGORY_VALUE",
  "NORTHSTAR_OPERATIONS_CATEGORY_VALUE",
  "northstarMarketingServices",
  "northstarOperationsServices",
  "northstarPackages",
  "northstarStatuses",
  "renderNorthStarPage",
  "renderPersonalDriverPage",
  "renderPaymentsPage",
  "renderLocalProductsPage",
  "workerTrustProfile",
  "workerTrustLedgerHtml",
  "jobSafetyGateHtml",
  "workerTrustTiers",
  "dispatchDecisionLabels",
  "personalDriverRequests",
  "personalDriverProviders",
  "merchantServiceLeads",
  "localProductVendors",
  "submitPersonalDriverRequest",
  "submitPersonalDriverProvider",
  "submitMerchantServicesLead",
  "submitLocalProductVendor",
  "forge-merchant-services",
  "local-product-vendor",
  "submitNorthStarLead",
  "northstarLeadText",
  "northstarLeadLines",
  "copyNorthStarBrief",
  "copyNorthStarQueue",
  "copyNorthStarLead",
  "markNorthStarContacted",
  "moveNorthStarForward",
  "northstar_marketing_operations",
  "flexLeadStatuses",
  "FORGE_CAPITAL_DESK_ENABLED",
  "FLEX_COMPLIANCE_COPY",
  "renderCapitalPage",
  "normalizeFlexLead",
  "calculateFlexLeadScore",
  "submitFlexLead",
  "renderFlexLeadsAdmin",
  "copyFlexBrief",
  "copyFlexQueue",
  "openFlexReferral",
  "createFlexUpsellTask",
  "forge-flex",
  "flex_link_sent",
  "provider_onboarding",
  "BuildTrackerDashboard",
  "ProjectSummaryCard",
  "GanttTimeline",
  "BudgetDashboard",
  "ExpenseReportTable",
  "ProjectTeamCard",
  "ChangeOrderCard",
  "DocumentVaultCard",
  "LatestUpdatesCard",
  "Sample Custom Home Build",
  "opportunityTracks",
  "opportunitySteps",
  "opportunityLeads",
  "renderOpportunities",
  "copyOpportunityPlan",
  "copyOpportunityLead",
  "copyOpportunityLeads",
  "opportunityLeadText",
  "opportunityLeadLines",
  "buildingLeadStatuses",
  "buildingLeadRouting",
  "normalizeBuildingLead",
  "renderBuildingPage",
  "renderAdminBuildingLeadsPage",
  "submitBuildingLead",
  "canSendBuildingToSeneca",
  "canSendBuildingToFlex",
  "FLEX_PARTNER_ROUTING_ENABLED = false",
  "SENECA_PARTNER_ROUTING_ENABLED = false",
  "copyBuildingQueue",
  "FLEX_APP_URL",
  "BUILDING_COMPLIANCE_COPY",
  "markOpportunityContacted",
  "moveOpportunityForward",
  "Forge opportunity application plan",
  "Forge career opportunity lead",
  "Trade school",
  "Union / apprenticeship",
  "Blue-collar AI jobs",
  "Career interest saved.",
  "markJobContacted",
  "moveJobForward",
  "moveWorkerForward",
  "moveReferralForward",
  "move-job-forward",
  "adminWorkersTable",
  "webhookUrl",
  "renderDeliveryStatus",
  "deliveryStatusRows",
  "copyDeliveryStatus",
  "renderLeadDeliveryDrill",
  "leadDeliveryDrillRows",
  "copyLeadDeliveryDrill",
  "Forge lead delivery drill",
  "Lead delivery drill",
  "updateWebhookDelivery",
  "renderBackendHandoff",
  "backendHandoffRows",
  "copyBackendHandoff",
  "Supabase schema prepared",
  "renderAuthHandoff",
  "authHandoffRows",
  "copyAuthHandoff",
  "renderAdminAuthDrill",
  "adminAuthDrillRows",
  "copyAdminAuthDrill",
  "Forge admin auth drill",
  "Admin auth drill",
  "Browser-only demo state is not production auth",
  "demoAccounts",
  "loginAs",
  "lastGuardedRoute",
  "recordGuardedRoute",
  "renderOperatorGuard",
  "Protected operator link",
  "Forge blocked direct public access to this operator screen.",
  "renderSession",
  "Log in as Forge Admin to open operator tools.",
  "expireAdminSession",
  "syncWorkerSession",
  "renderMessages",
  "messageSummary",
  "messageFlowMarkup",
  "messageProofReceipt",
  "messageProofReceiptTitle",
  "messageProofReceiptText",
  "messageReplyKit",
  "messageReplyKitRows",
  "messageReplyText",
  "Copy Message Proof",
  "Copy Reply Kit",
  "copyMessageProof",
  "copyMessageReplyKit",
  "Forge message reply kit",
  "Message proof copied.",
  "Message reply kit copied.",
  "Job to bid to message flow",
  "Handoff ready",
  "messageContext",
  "saveMessageDraft",
  "loadCustomerStatus",
  "renderReports",
  "customerStatusProofSummary",
  "statusProofPrimaryAction",
  "statusProofSummaryRows",
  "Copy Status Proof",
  "copyStatusProofSummary",
  "Status proof copied.",
  "confirmNextSteps",
  "confirmationCloseoutRows",
  "confirmationNextTouchRows",
  "confirmationNextTouchTitle",
  "confirmationNextTouchSummary",
  "confirmationHandoffTitle",
  "confirmationHandoffText",
  "copyConfirmationHandoff",
  "copyConfirmationNextTouch",
  "Confirmation handoff copied.",
  "Copy Next Touch",
  "Next touch copied.",
  "Manual review before any outside handoff.",
  "Forge saved this job on this device before attempting delivery",
  "reportItem",
  "renderProfileStatus",
  "getProfileStatus",
  "demo-paths",
  "perspective-demo",
  "readinessCard",
  "profileReadiness",
  "renderProfilePerspectiveSwitch",
  "profilePerspectiveRows",
  "profilePerspectiveTitle",
  "copyProfilePerspective",
  "Forge profile perspective lens",
  "Perspective switch",
  "renderProfileCommandStrip",
  "profileCommandRows",
  "profileCommandProof",
  "profileVisibilityPanel",
  "profileVisibilityRows",
  "profileVisibilityTitle",
  "copyProfileCommand",
  "profileStatusReceiptPanel",
  "profileStatusReceiptRows",
  "copyProfileStatusReceipt",
  "Forge profile status receipt",
  "copyProfileVisibility",
  "Forge profile command",
  "Forge profile visibility",
  "renderLaunchHandoffReceipt",
  "launchHandoffReceiptRows",
  "firstUserHandoffNote",
  "copyLaunchHandoffReceipt",
  "Forge first-user handoff receipt",
  "profileBriefRows",
  "profileDemoHandoff",
  "profileDemoHandoffRows",
  "Perspective handoff",
  "profileCloseCard",
  "copyProfileCloseAsk",
  "Forge profile close ask",
  "Close ask",
  "copyProfileDemoHandoff",
  "Forge profile demo handoff",
  "profileProofPathRows",
  "copyProfileProofPath",
  "Forge profile proof path",
  "renderWorkerOpportunityBridge",
  "workerOpportunityBridgeRows",
  "copyWorkerOpportunityBridge",
  "Forge worker opportunity bridge",
  "Worker opportunity bridge",
  "workerOpportunityBridgeTitle",
  "copyProfileBrief",
  "Forge profile status brief",
  "workerProfileStatus",
  "customerProfileStatus",
  "perspectiveCards",
  "renderPerspective",
  "renderPerspectiveSwitchRail",
  "perspectiveSwitchRailRows",
  "copyPerspectiveSwitchRail",
  "Forge perspective switch rail",
  "Perspective switch rail",
  "demoProofSwitchboardRows",
  "renderDemoProofSwitchboard",
  "renderPhoneFastPass",
  "phoneFastPassRows",
  "copyPhoneFastPass",
  "Forge phone demo fast pass",
  "Copy Fast Pass",
  "data-demo-proof-role",
  "perspectiveReadinessGrid",
  "renderPerspectiveReadiness",
  "perspectiveReadinessRows",
  "demoGuide",
  "renderDemoGuide",
  "demoCueCards",
  "renderDemoCueCards",
  "copyDemoCue",
  "Copy Cue",
  "You should be able to see what is happening with your job",
  "renderLaunchReceipt",
  "launchReceiptRows",
  "copyLaunchReceipt",
  "Forge first-user launch receipt",
  "demoPaths",
  "renderDemoPath",
  "demo-route-actions",
  "renderDemoLinks",
  "customerDemoJobPriority",
  "Homeowner proof",
  "Forge Auto services proof",
  "Auto buyer / seller",
  "Forge Auto can capture vehicle service",
  "autoLeadRouteRows",
  "Soft launch route",
  "Forge Auto Services:",
  "renderDemoOutcomes",
  "renderNavigationState",
  "renderFinishChecklist",
  "Bottom tab bar includes Home, Services, Post, Jobs, Account, plus Demo, Launch, Status, Messages, and Profile shortcuts.",
  "On mobile, run John Status, John Messages, Mike Worker proof, then Launch Status in under one minute.",
  "copyDemoScript",
  "copyDemoPack",
  "copyDemoLink",
  "copyCloseAsk",
  "renderSafetyCenter",
  "renderSoftLaunchPlan",
  "softLaunchRows",
  "renderSoftLaunchInvites",
  "softLaunchInviteRows",
  "renderSoftLaunchRunSheet",
  "softLaunchRunSheetRows",
  "copySoftLaunchPlan",
  "copySoftLaunchInvite",
  "copySoftLaunchInviteKit",
  "copySoftLaunchRunSheet",
  "renderLaunchDemoPack",
  "launchDemoPackRows",
  "renderLaunchDecision",
  "launchDecisionRows",
  "copyLaunchDecision",
  "Forge soft launch decision",
  "renderPublicLaunchBlockers",
  "publicLaunchBlockerRows",
  "publicLaunchBlockerRow",
  "copyPublicLaunchBlockers",
  "Forge public launch blocker receipt",
  "Copy Blockers",
  "renderLaunchSecuritySweep",
  "launchSecuritySweepRows",
  "copyLaunchSecuritySweep",
  "Forge public share safety sweep",
  "Public share safety sweep",
  "renderPublicLaunchGoNoGo",
  "publicLaunchGoNoGoRows",
  "copyPublicLaunchGoNoGo",
  "Forge public launch go / no-go receipt",
  "Controlled demos are GO",
  "renderLaunchShowPlan",
  "launchShowPlanRows",
  "copyLaunchShowPlan",
  "Forge launch show plan",
  "Copy Show Plan",
  "Controlled demos and first-user signups",
  "renderLaunchFinalChecklist",
  "launchFinalChecklistRows",
  "launchRunOrderPanel",
  "launchRunOrderRows",
  "copyLaunchFinalChecklist",
  "copyLaunchRunOrder",
  "Forge final first-user checklist",
  "Forge first-user demo run order",
  "Copy Run Order",
  "renderLaunchSendBoard",
  "firstUserSendBoardRows",
  "copyLaunchSendBoard",
  "copyLaunchSendLink",
  "Forge first-user send board",
  "Copy Send Board",
  "renderLaunchNext10Sprint",
  "launchNext10SprintRows",
  "copyLaunchNext10Sprint",
  "Forge next 10 invite sprint",
  "canRenderPrivateOperatorData",
  "redactPrivateOperatorSurfaces",
  "operatorRedactionCard",
  "Private operator data hidden",
  "renderCaptureTriageBoard",
  "captureTriageRows",
  "copyCaptureTriage",
  "copyLatestCapturedLead",
  "Forge quick capture triage",
  "jobProofTicketPanel",
  "jobProofTicketRows",
  "copyJobProofTicket",
  "Forge job proof ticket",
  "renderFirstUserCountBreakdown",
  "firstUserLeadBreakdownRows",
  "copyFirstUserCountBreakdown",
  "Forge first-user count breakdown",
  "renderFirst200LaunchQueue",
  "first200LaunchQueueRows",
  "copyFirst200LaunchQueue",
  "Forge First 200 launch queue",
  "Manual-review leads stay guarded",
  "Auto sellers, buyers, and service requests",
  "Driver, merchant, and local product leads",
  "John proof path",
  "Forge soft launch tomorrow plan",
  "Forge soft launch invite kit",
  "Forge launch day run sheet",
  "John Customer Proof",
  "Mike Worker Proof",
  "Controlled soft launch only",
  "launchGateRows",
  "Ready for controlled signups",
  "Do not send broadly yet",
  "copyLaunchGate",
  "deployPreflightRows",
  "publicReadinessSummary",
  "publicReadinessBlockers",
  "Public beta readiness gate",
  "This is a demo-readiness score, not launch approval.",
  "finalSecurityGate",
  "Static host security config",
  "Lead capture backend",
  "Demo admin guard",
  "copyDeployPlan",
  "copyReleaseCandidatePacket",
  "Forge public beta release candidate packet",
  "copyLaunchRunbook",
  "Forge public beta deploy runbook",
  "copySecurityCommand",
  "npm run check",
  "copyFinalSecurityGate",
  "finalSecurityGateRows",
  "Forge final public gate",
  "copySecurityReviewPack",
  "Forge final public security review",
  "safetyChecks",
  "copySafetyChecklist",
  "lastBackupLeadCount",
  "renderFirstUserCloseout",
  "firstUserCloseoutRows",
  "copyFirstUserCloseout",
  "Forge first-user closeout",
  "renderFollowUpAudit",
  "followUpAuditRows",
  "copyFollowUpAudit",
  "Forge first-user follow-up audit",
  "renderLaunchCommandCenter",
  "launchCommandRows",
  "launchCommandKinds",
  "copyLaunchCommand",
  "copyLaunchCommandRow",
  "Copy Lane",
  "renderOutreachRecap",
  "outreachRecapSummary",
  "copyOutreachRecap",
  "renderOutreachSprintBrief",
  "outreachSprintBriefRows",
  "copyOutreachSprintPlan",
  "Forge next 10 sprint plan",
  "renderOutreachBatch",
  "outreachBatchRows",
  "copyOutreachBatch",
  "renderFollowUpCommandStrip",
  "followUpCommandRows",
  "copyFollowUpCommand",
  "Forge follow-up command",
  "completeOutreachSprint",
  "Outreach sprint completed",
  "renderSessionHistory",
  "outreachSessionHistory",
  "copySessionHistory",
  "copySessionNote",
  "Selected bid handoff",
  "Choose + Message",
  "Choose Suggested Bid",
  "chooseSuggestedBidForJob",
  "suggestedBidIndex",
  "Open John's Messages",
  "loginRole",
  "loginThread",
  "Open Thread",
  "chosenBidHandoff",
  "bidHandoffText",
  "copyBidHandoff",
  "copy-job-handoff-rail",
  "jobCloseoutPanel",
  "jobCloseoutRows",
  "copyJobCloseout",
  "Forge job closeout receipt",
  "demoCloseLoop",
  "demoCloseLoopRows",
  "demoCloseLoopSummary",
  "messageDemoCloseLoop",
  "copyDemoCloseLoop",
  "Forge demo close loop",
  "Demo close loop",
  "Copy Loop",
  "messageHandoffPanel",
  "messageHandoffRows",
  "copyMessageHandoff",
  "Forge message handoff closeout",
  "messageProofBridge",
  "messageBridgeRows",
  "copyMessageBridge",
  "Forge message proof bridge",
  "copyMessageReplyKit",
  "Forge message reply kit",
  "copyStatusHandoff",
  "Forge customer status handoff",
  "closeAskText",
  "roleDemoLink",
  "copyPerspectiveLink",
  "perspectiveLink",
  "copy-perspective-link",
  "demo=",
  "Bid chosen.",
  "View as"
];

const html = await readFile("index.html", "utf8");
const js = await readFile("app.js", "utf8");
const css = await readFile("styles.css", "utf8");
const manifest = await readFile("manifest.webmanifest", "utf8");
const serviceWorker = await readFile("service-worker.js", "utf8");
const netlify = await readFile("netlify.toml", "utf8");
const vercel = await readFile("vercel.json", "utf8");
const robots = await readFile("robots.txt", "utf8");
const securityReview = await readFile("SECURITY_REVIEW_CHECKLIST.md", "utf8");
const supabaseSchema = await readFile("SUPABASE_SCHEMA.sql", "utf8");
const webhookPayloads = await readFile("WEBHOOK_PAYLOADS.md", "utf8");
const adminAuthPlan = await readFile("ADMIN_AUTH_PLAN.md", "utf8");
const securityCheck = await readFile("security-check.mjs", "utf8");
const deployRunbook = await readFile("PUBLIC_BETA_DEPLOY_RUNBOOK.md", "utf8");
const releaseManifest = await readFile("release-manifest.json", "utf8");
const releaseCandidate = await readFile("RELEASE_CANDIDATE.md", "utf8");
const releaseCheck = await readFile("release-check.mjs", "utf8");
const packageJson = await readFile("package.json", "utf8");
const githubWorkflow = await readFile(".github/workflows/forge-checks.yml", "utf8");
const finalPublicGate = await readFile("FINAL_PUBLIC_GATE.md", "utf8");
const autoDealerIntegration = await readFile("AUTO_DEALER_INTEGRATION.md", "utf8");
const requestHelpRoute = await readFile("request-help/index.html", "utf8");
const postJobRoute = await readFile("post-job/index.html", "utf8");
const workerSignupRoute = await readFile("worker-signup/index.html", "utf8");
const businessRoute = await readFile("business/index.html", "utf8");
const financialReadinessRoute = await readFile("financial-readiness/index.html", "utf8");
const financialReadinessStyles = await readFile("financial-readiness/financial-readiness.css", "utf8");
const photographyRoute = await readFile("photography/index.html", "utf8");
const photographyRequestRoute = await readFile("photography/request/index.html", "utf8");
const photographyApplyRoute = await readFile("photography/apply/index.html", "utf8");
const creativeRoute = await readFile("photography-videography/index.html", "utf8");
const northstarRoute = await readFile("northstar-creative/index.html", "utf8");
const buildingRoute = await readFile("building/index.html", "utf8");
const adminBuildingRoute = await readFile("admin/building-leads/index.html", "utf8");
const forgeAcademyRoute = await readFile("forge-academy/index.html", "utf8");
const forgeAcademyApplyRoute = await readFile("forge-academy/apply/index.html", "utf8");
const forgeAcademyEmployersRoute = await readFile("forge-academy/employers/index.html", "utf8");
const forgeAcademySchoolsRoute = await readFile("forge-academy/schools/index.html", "utf8");
const forgeCareerDashboardRoute = await readFile("dashboard/career/index.html", "utf8");
const admitlyTradePathwaysRoute = await readFile("trade-pathways/index.html", "utf8");
const admitlyTradePathwaysApplyRoute = await readFile("trade-pathways/apply/index.html", "utf8");
const admitlyTradePathwaysDashboardRoute = await readFile("dashboard/trade-pathways/index.html", "utf8");
const adminForgeAcademyRoute = await readFile("admin/forge-academy/index.html", "utf8");
const adminTradePathwaysRoute = await readFile("admin/trade-pathways/index.html", "utf8");
const forgeCapitalRoute = await readFile("forge/capital/index.html", "utf8");
const forgeFlexRoute = await readFile("forge/flex/index.html", "utf8");
const partnersFlexRoute = await readFile("partners/flex/index.html", "utf8");
const personalDriverRoute = await readFile("personal-driver/index.html", "utf8");
const privateDriverRoute = await readFile("private-driver/index.html", "utf8");
const forgePaymentsRoute = await readFile("forge-payments/index.html", "utf8");
const merchantServicesRoute = await readFile("merchant-services/index.html", "utf8");
const localProductsRoute = await readFile("local-products/index.html", "utf8");
const makersRoute = await readFile("makers/index.html", "utf8");
const flexMigration = await readFile("migrations/20260626_forge_flex_leads.sql", "utf8");
const flexReadme = await readFile("docs/forge-capital-desk-readme.md", "utf8");
const flexOutreach = await readFile("docs/forge-flex-capital-desk-outreach.md", "utf8");
const admitlyTradePathwaysDoc = await readFile("docs/admitly-trade-pathways.md", "utf8");
const forgeAcademyDoc = await readFile("docs/forge-academy.md", "utf8");
const admitlyForgeBridgeDoc = await readFile("docs/admitly-forge-career-bridge.md", "utf8");
const forgeCareerPlusDoc = await readFile("docs/forge-career-plus.md", "utf8");
const flexApiRoute = await readFile("api/forge/flex-leads/route.ts", "utf8");
const flexApiEntrypoint = await readFile("api/forge/flex-leads.ts", "utf8");
const envExample = await readFile(".env.example", "utf8");
const requiredTradeLabels = [
  "Electrician",
  "Plumbing",
  "HVAC",
  "Roofing",
  "Carpentry",
  "Welding",
  "Concrete",
  "Masonry",
  "Heavy Equipment",
  "CDL Training",
  "Diesel Mechanics",
  "Automotive",
  "Landscaping",
  "Arborist",
  "Solar Installation",
  "Fiber Optics",
  "Low Voltage Systems",
  "Appliance Repair",
  "Painting",
  "General Contracting"
];
const missingTradeLabels = requiredTradeLabels.filter((label) => !js.includes(`label: "${label}"`) && !js.includes(`category: "${label}"`) && !js.includes(`categoryLabel: "${label}"`));
const missingTradeHooks = [
  ["customer job category", html.includes("id=\"jobCategory\"")],
  ["service job details", html.includes("id=\"serviceJobFields\"")],
  ["provider vertical", html.includes("id=\"workerServiceVertical\"")],
  ["provider trade categories", html.includes("id=\"workerTradeCategories\"")],
  ["provider profile fields", html.includes("id=\"providerProfileFields\"")],
  ["job board category filter", html.includes("id=\"listingCategory\"")],
  ["provider directory filter", html.includes("id=\"providerVerticalFilter\"")],
  ["admin category filter", html.includes("id=\"adminTradeCategoryFilter\"")],
  ["homepage trade grid", html.includes("id=\"requiredTradeCategoryGrid\"")],
  ["central trade schema", js.includes("forgeTradeCategorySchema")]
].filter(([, ok]) => !ok).map(([label]) => label);

const missingHtml = requiredHtml.filter((text) => !html.includes(text));
const missingJs = requiredJs.filter((text) => !js.includes(text));
const missingCss = [
  ["safe-area mobile tabbar", css.includes("env(safe-area-inset-bottom)")],
  ["compact phone feature strip", css.includes(".feature-strip") && css.includes("repeat(3, minmax(0, 1fr))")],
  ["auto services", css.includes(".auto-layout") && css.includes(".auto-card") && css.includes(".auto-sell-card") && css.includes(".auto-service-grid")],
  ["auto transport and platinum", css.includes(".auto-transport-grid") && css.includes(".forge-platinum-panel")],
  ["auto admin operations", css.includes(".auto-admin-ops") && css.includes(".auto-admin-columns") && css.includes(".operations-vault-grid")],
  ["auto service requests", css.includes(".auto-request-section") && css.includes(".auto-request-list") && css.includes(".auto-service-form")],
  ["auto dealer network", css.includes(".auto-dealer-grid") && css.includes(".auto-dealers")],
  ["auto dealer setup", css.includes(".auto-setup-grid") && css.includes(".auto-setup")],
  ["auto buyer inquiries", css.includes(".auto-inquiries") && css.includes(".auto-inquiry-list")],
  ["auto lead route", css.includes(".auto-route-grid") && css.includes(".auto-route")],
  ["photography videography page", css.includes(".creative-layout") && css.includes(".creative-service-grid") && css.includes(".creative-provider-panel")],
  ["photography quality notes", css.includes(".creative-quality") && css.includes(".creative-booking-notes") && css.includes(".creative-disclaimer")],
  ["northstar creative page", css.includes(".northstar-layout") && css.includes(".northstar-package-grid") && css.includes(".northstar-intake-panel")],
  ["northstar lead cards", css.includes(".northstar-chip-grid") && css.includes(".northstar-lead-list")],
  ["building page", css.includes(".building-hero") && css.includes(".building-intake-card") && css.includes(".building-card-grid")],
  ["capital desk page", css.includes(".capital-layout") && css.includes(".capital-hero") && css.includes(".capital-form-panel")],
  ["flex admin and status", css.includes(".flex-status") && css.includes(".flex-admin-section") && css.includes(".flex-filter-row")],
  ["provider growth tools", css.includes(".provider-growth-tools")],
  ["homebuilding page", css.includes(".homebuilding-layout") && css.includes(".tracker-feature-card")],
  ["build tracker dashboard", css.includes(".build-tracker-dashboard") && css.includes(".tracker-card")],
  ["build tracker gantt", css.includes(".gantt-scroll") && css.includes(".gantt-bar")],
  ["build tracker budget", css.includes(".budget-category-grid") && css.includes(".budget-alerts")],
  ["training careers hub", css.includes(".opportunity-layout") && css.includes(".opportunity-track-grid") && css.includes(".opportunity-lead-list")],
  ["forge academy and admitly pages", css.includes(".academy-layout") && css.includes(".academy-option-grid") && css.includes(".admitly-layout") && css.includes(".admitly-path-grid")],
  ["forge marketplace and admitly presentation", css.includes(".marketplace-entry-panel") && css.includes(".marketplace-command-grid") && css.includes(".customer-dashboard-layout") && css.includes(".admitly-presentation-screen") && css.includes(".admitly-dashboard-demo")],
  ["forge account and customer profile panels", css.includes(".account-auth-panel") && css.includes(".account-auth-form") && css.includes(".account-auth-status") && css.includes(".customer-profile-form")],
  ["academy admin grids", css.includes(".academy-admin-stats") && css.includes(".academy-partner-grid")],
  ["soft launch plan", css.includes(".soft-launch-grid") && css.includes(".soft-launch")],
  ["launch run checklist", css.includes(".launch-run-card") && css.includes(".launch-run-grid")],
  ["demo command strip", css.includes(".demo-command-strip") && css.includes(".demo-command-actions")],
  ["perspective readiness receipt", html.includes("perspectiveReadinessGrid") && css.includes(".perspective-readiness") && css.includes(".perspective-readiness-grid") && js.includes("renderPerspectiveReadiness")],
  ["outreach sprint brief", css.includes(".outreach-sprint-brief") && js.includes("copy-outreach-sprint-plan")],
  ["phone demo order", css.includes(".mobile-demo-flow") && css.includes(".mobile-demo-flow-grid") && css.includes(".mobile-demo-closeout") && css.includes(".mobile-demo-closeout-actions") && css.includes("grid-template-columns: repeat(4, minmax(0, 1fr))") && html.includes("Open Msgs") && html.includes("Phone closeout")],
  ["phone fast pass", html.includes("phoneFastPass") && css.includes(".phone-fast-pass") && css.includes(".phone-fast-pass-grid") && js.includes("renderPhoneFastPass") && js.includes("phoneFastPassRows") && js.includes("copyPhoneFastPass")],
  ["perspective switch rail", html.includes("perspectiveSwitchRail") && css.includes(".perspective-switch-rail") && css.includes(".perspective-switch-grid") && js.includes("renderPerspectiveSwitchRail") && js.includes("perspectiveSwitchRailRows") && js.includes("copyPerspectiveSwitchRail")],
  ["demo proof switchboard", html.includes("demoProofSwitchboard") && css.includes(".demo-proof-switchboard") && css.includes(".demo-proof-grid") && js.includes("renderDemoProofSwitchboard")],
  ["wireframe alignment layer", css.includes("Forge wireframe alignment layer") && css.includes("--wire-blue") && css.includes(".home-top .brand")],
  ["premium service marketplace", html.includes("premiumServiceGrid") && css.includes(".premium-marketplace") && css.includes(".premium-service-card") && js.includes("renderPremiumMarketplace")],
  ["wireframe orange price accents", css.includes(".job-price,") && css.includes("color: var(--wire-orange)")],
  ["first user start path", css.includes(".start-path-grid") && css.includes(".start-path-card")],
  ["first user path heading", css.includes(".start-path-heading")],
  ["signup readiness panel", css.includes(".signup-readiness-panel") && css.includes(".readiness-grid")],
  ["worker soft launch consent card", css.includes(".worker-soft-launch-card") && css.includes(".worker-soft-launch-grid")],
  ["worker opportunity bridge", html.includes("workerOpportunityBridge") && css.includes(".worker-opportunity-bridge") && css.includes(".worker-opportunity-grid") && js.includes("renderWorkerOpportunityBridge") && js.includes("workerOpportunityBridgeRows") && js.includes("copyWorkerOpportunityBridge")],
  ["capture triage board", html.includes("captureTriageBoard") && css.includes(".capture-triage-board") && css.includes(".capture-triage-grid") && js.includes("renderCaptureTriageBoard") && js.includes("copyCaptureTriage")],
  ["job handoff rail", css.includes(".job-handoff-rail") && css.includes(".job-handoff-rail-grid") && js.includes("jobHandoffRail") && js.includes("jobHandoffRailRows") && js.includes("copyJobHandoffRail")],
  ["status message bridge", css.includes(".status-message-bridge") && css.includes(".status-message-bridge-grid") && js.includes("statusMessageBridge") && js.includes("statusMessageBridgeRows") && js.includes("copyStatusMessageBridge")],
  ["message context bridge", css.includes(".message-context-bridge") && css.includes(".message-context-bridge-grid") && js.includes("messageContextBridge") && js.includes("messageContextBridgeRows")],
  ["job proof ticket", css.includes(".job-proof-ticket") && css.includes(".job-proof-ticket-grid") && js.includes("jobProofTicketPanel") && js.includes("copyJobProofTicket")],
  ["public operator link guard", css.includes(".public-link-guard") && css.includes(".public-link-guard-actions")],
  ["profile login prompt", html.includes("Profile status login note") && css.includes(".profile-login-prompt")],
  ["launch gate panel", css.includes(".launch-gate") && css.includes(".launch-gate-card.blocked")],
  ["launch decision card", css.includes(".launch-decision-card") && css.includes(".launch-decision-actions")],
  ["launch final checklist", html.includes("launchFinalChecklist") && css.includes(".launch-final-checklist") && css.includes(".launch-final-grid") && js.includes("renderLaunchFinalChecklist") && js.includes("copyLaunchFinalChecklist")],
  ["launch security sweep", html.includes("launchSecuritySweep") && css.includes(".launch-security-sweep") && css.includes(".launch-security-grid") && js.includes("renderLaunchSecuritySweep") && js.includes("copyLaunchSecuritySweep")],
  ["public launch go no-go receipt", html.includes("publicLaunchGoNoGo") && css.includes(".public-launch-go-no-go") && css.includes(".public-launch-go-no-go-grid") && js.includes("renderPublicLaunchGoNoGo") && js.includes("copyPublicLaunchGoNoGo")],
  ["launch show plan", html.includes("launchShowPlan") && css.includes(".launch-show-plan") && css.includes(".launch-show-plan-grid") && js.includes("renderLaunchShowPlan") && js.includes("launchShowPlanRows") && js.includes("copyLaunchShowPlan")],
  ["launch run order", css.includes(".launch-run-order") && css.includes(".launch-run-order-grid") && js.includes("launchRunOrderPanel") && js.includes("launchRunOrderRows") && js.includes("copyLaunchRunOrder")],
  ["launch send board", html.includes("launchSendBoard") && css.includes(".launch-send-board") && css.includes(".launch-send-grid") && js.includes("renderLaunchSendBoard") && js.includes("copyLaunchSendBoard")],
  ["launch handoff receipt", html.includes("launchHandoffReceipt") && css.includes(".launch-handoff-receipt") && css.includes(".launch-handoff-grid") && js.includes("renderLaunchHandoffReceipt") && js.includes("launchHandoffReceiptRows") && js.includes("copyLaunchHandoffReceipt")],
  ["launch next 10 sprint", html.includes("launchNext10Sprint") && css.includes(".launch-next-10-sprint") && css.includes(".launch-next-10-grid") && css.includes(".launch-next-10-actions") && js.includes("renderLaunchNext10Sprint") && js.includes("copyLaunchNext10Sprint")],
  ["private operator redaction", css.includes(".operator-redaction-card") && js.includes("canRenderPrivateOperatorData") && js.includes("redactPrivateOperatorSurfaces") && js.includes("operatorRedactionCard")],
  ["launch command lane actions", css.includes(".launch-command-actions") && js.includes("copy-launch-command-row")],
  ["deploy preflight panel", css.includes(".deploy-preflight") && css.includes(".deploy-grid")],
  ["readiness score panel", css.includes(".readiness-score") && css.includes(".readiness-score h3")],
  ["profile status receipt", html.includes("profileStatusReceipt") && css.includes(".profile-status-receipt") && css.includes(".profile-status-receipt-grid") && js.includes("profileStatusReceiptPanel") && js.includes("copyProfileStatusReceipt")],
  ["profile perspective switch", html.includes("profilePerspectiveSwitch") && css.includes(".profile-perspective-switch") && css.includes(".profile-perspective-grid") && js.includes("renderProfilePerspectiveSwitch") && js.includes("profilePerspectiveRows") && js.includes("copyProfilePerspective")],
  ["profile command strip", html.includes("profileCommandStrip") && css.includes(".profile-command-strip") && js.includes("renderProfileCommandStrip") && js.includes("copyProfileCommand")],
  ["profile visibility panel", html.includes("profileVisibilityPanel") && css.includes(".profile-visibility-panel") && css.includes(".profile-visibility-grid") && js.includes("profileVisibilityPanel") && js.includes("profileVisibilityRows") && js.includes("copyProfileVisibility")],
  ["profile brief panel", css.includes(".profile-brief-grid") && css.includes(".profile-brief-heading")],
  ["profile demo handoff", css.includes(".profile-demo-handoff") && css.includes(".profile-demo-handoff-grid")],
  ["profile proof path", css.includes(".profile-proof-path") && css.includes(".profile-proof-heading")],
  ["bid message flow panel", css.includes(".bid-flow-panel") && css.includes(".message-flow")],
  ["bid action panel", css.includes(".bid-action-panel") && js.includes("Choose + Message") && js.includes("Open Thread")],
  ["bid demo handoff actions", css.includes(".demo-handoff-actions") && css.includes("grid-template-columns: repeat(2, minmax(0, 1fr))")],
  ["worker proof actions", css.includes(".worker-proof-card") && css.includes(".worker-proof-actions")],
  ["customer status demo strip", css.includes(".status-demo-strip") && css.includes(".status-demo-actions")],
  ["demo route primary actions", css.includes(".demo-route-actions") && js.includes("index === 0 ? \"blue\" : \"ghost\"")],
  ["launch receipt panel", html.includes("launchReceiptGrid") && css.includes(".launch-receipt-grid") && js.includes("renderLaunchReceipt") && js.includes("copyLaunchReceipt")],
  ["public launch blocker receipt", html.includes("publicLaunchBlockers") && css.includes(".public-launch-blockers") && css.includes(".public-launch-blocker-grid") && js.includes("renderPublicLaunchBlockers") && js.includes("copyPublicLaunchBlockers")],
  ["first user count breakdown", html.includes("firstUserCountBreakdown") && css.includes(".first-user-breakdown-grid") && js.includes("renderFirstUserCountBreakdown") && js.includes("copyFirstUserCountBreakdown")],
  ["first 200 launch queue", html.includes("first200QueueGrid") && css.includes(".first-200-queue-grid") && js.includes("renderFirst200LaunchQueue") && js.includes("copyFirst200LaunchQueue")],
  ["mobile demo shortcuts", html.includes('aria-label="Forge demo shortcuts"') && html.includes('aria-label="Open customer status">Status</button>') && html.includes('aria-label="Open messages">Msgs</button>') && html.includes('aria-label="Open profile status">Profile</button>') && css.includes(".mobile-tabbar-secondary") && css.includes("flex: 1 1 0")],
  ["final gate panel", css.includes(".final-gate") && css.includes(".final-gate article.hold")],
  ["delivery status panel", css.includes(".delivery-status") && css.includes(".delivery-grid")],
  ["lead delivery drill", html.includes("leadDeliveryDrill") && css.includes(".delivery-drill-grid") && js.includes("renderLeadDeliveryDrill") && js.includes("copyLeadDeliveryDrill")],
  ["backend handoff panel", css.includes(".backend-handoff") && css.includes(".backend-grid")],
  ["auth handoff panel", css.includes(".auth-handoff") && css.includes(".auth-grid")],
  ["admin auth drill", html.includes("adminAuthDrill") && css.includes(".auth-drill-grid") && js.includes("renderAdminAuthDrill") && js.includes("copyAdminAuthDrill")],
  ["first user closeout panel", css.includes(".first-user-closeout-grid") && css.includes(".first-user-closeout-card")],
  ["launch demo pack panel", css.includes(".launch-demo-pack") && css.includes(".launch-demo-pack-grid")],
  ["legal screen", css.includes(".legal-layout") && css.includes(".legal-grid")],
  ["confirmation next steps", css.includes(".confirm-next") && css.includes(".confirm-next article")],
  ["confirmation handoff", css.includes(".confirm-handoff") && css.includes("border-left: 6px solid var(--orange)")],
  ["confirmation next touch", html.includes("confirmFollowUp") && css.includes(".confirm-follow-up-grid") && js.includes("confirmationNextTouchRows") && js.includes("copyConfirmationNextTouch")],
  ["job flow tracker", css.includes(".job-flow-grid") && css.includes(".job-flow-grid article.active")],
  ["job flow brief", css.includes(".job-flow-brief-grid") && css.includes(".job-flow-brief-heading")],
  ["job detail handoff panel", css.includes(".detail-handoff-panel") && css.includes(".detail-handoff-grid") && css.includes(".detail-handoff-actions")],
  ["job closeout panel", css.includes(".job-closeout-panel") && css.includes(".job-closeout-grid") && css.includes(".job-closeout-actions") && js.includes("jobCloseoutPanel") && js.includes("copyJobCloseout")],
  ["demo close loop", css.includes(".demo-close-loop") && css.includes(".demo-close-loop-grid") && css.includes(".demo-close-loop-actions") && js.includes("demoCloseLoop") && js.includes("messageDemoCloseLoop") && js.includes("copyDemoCloseLoop")],
  ["status empty guidance", css.includes(".status-empty")],
  ["customer status demo card", css.includes(".status-demo-card") && css.includes("#fff7ef")],
  ["customer status flow panel", css.includes(".status-flow-panel")],
  ["customer status proof summary", css.includes(".status-proof-summary") && css.includes(".status-proof-grid") && css.includes(".status-proof-actions") && js.includes("customerStatusProofSummary") && js.includes("copyStatusProofSummary")],
  ["customer status handoff panel", css.includes(".status-handoff-panel") && css.includes(".status-handoff-grid") && css.includes(".status-handoff-actions")],
  ["admin safety grid", css.includes(".safety-grid") && css.includes(".safety-item.attention")],
  ["follow-up audit panel", html.includes("followUpAuditGrid") && css.includes(".follow-up-audit-grid") && js.includes("renderFollowUpAudit") && js.includes("copyFollowUpAudit")],
  ["follow-up command strip", html.includes("followUpCommandStrip") && css.includes(".follow-up-command-strip") && js.includes("renderFollowUpCommandStrip") && js.includes("copyFollowUpCommand")],
  ["launch command cards", css.includes(".launch-command-grid") && css.includes(".command-meter")],
  ["outreach recap grid", css.includes(".outreach-recap-grid") && css.includes(".recap-list")],
  ["next 10 outreach batch", css.includes(".next-batch-list") && css.includes(".batch-row")],
  ["compact action buttons", css.includes(".compact-actions")],
  ["session history cards", css.includes(".session-history-list") && css.includes(".session-card")],
  ["selected bid handoff card", css.includes(".handoff-card") && css.includes(".handoff-grid")],
  ["message handoff closeout", html.includes("messageHandoffPanel") && css.includes(".message-handoff-panel") && css.includes(".message-handoff-grid") && js.includes("messageHandoffPanel") && js.includes("copyMessageHandoff")],
  ["message proof receipt", css.includes(".message-proof-receipt") && css.includes(".message-proof-actions") && js.includes("messageProofReceipt") && js.includes("copyMessageProof")],
  ["message proof bridge", css.includes(".message-bridge") && css.includes(".message-bridge-grid") && css.includes(".message-bridge-actions") && js.includes("messageProofBridge") && js.includes("messageBridgeRows") && js.includes("copyMessageBridge")],
  ["message reply kit", css.includes(".message-reply-kit") && css.includes(".message-reply-grid") && js.includes("messageReplyKit") && js.includes("messageReplyKitRows") && js.includes("copyMessageReplyKit") && js.includes("Forge message reply kit")]
].filter(([, ok]) => !ok).map(([label]) => label);
const missingPwa = [
  ["manifest link", html.includes("manifest.webmanifest")],
  ["service worker registration", js.includes("registerServiceWorker")],
  ["manifest name", manifest.includes("Forge MVP")],
  ["service worker cache", serviceWorker.includes("CACHE_NAME")],
  ["fresh service worker cache", serviceWorker.includes('FORGE_RELEASE = "133"')]
].filter(([, ok]) => !ok).map(([label]) => label);
const missingDeploy = [
  ["netlify security headers", netlify.includes("Content-Security-Policy") && netlify.includes("X-Frame-Options")],
  ["netlify spa redirect", netlify.includes("[[redirects]]") && netlify.includes("/index.html")],
  ["vercel security headers", vercel.includes("Content-Security-Policy") && vercel.includes("Permissions-Policy")],
  ["vercel rewrite", vercel.includes("\"rewrites\"") && vercel.includes("\"/index.html\"")],
  ["robots present", robots.includes("User-agent: *")],
  ["security review checklist", securityReview.includes("Forge Security Review Checklist") && securityReview.includes("Launch Decision")],
  ["supabase schema", supabaseSchema.includes("forge_job_leads") && supabaseSchema.includes("forge_opportunity_leads") && supabaseSchema.includes("trade_pathway_leads") && supabaseSchema.includes("forge_academy_leads") && supabaseSchema.includes("forge_career_profiles") && supabaseSchema.includes("school_partners") && supabaseSchema.includes("employer_training_partners") && supabaseSchema.includes("resume_requests") && supabaseSchema.includes("photography_videography") && supabaseSchema.includes("creative_service_requests") && supabaseSchema.includes("creative_provider_applications") && supabaseSchema.includes("northstar_marketing_operations_leads") && supabaseSchema.includes("forge_flex_leads") && supabaseSchema.includes("personal_driver_requests") && supabaseSchema.includes("personal_driver_provider_applications") && supabaseSchema.includes("forge_merchant_service_leads") && supabaseSchema.includes("local_product_vendor_leads") && supabaseSchema.includes("worker_trust_proof_ledger") && supabaseSchema.includes("building_leads") && supabaseSchema.includes("forge_vehicle_seller_leads") && supabaseSchema.includes("forge_operations_vault_documents") && supabaseSchema.includes("enable row level security")],
  ["webhook payload docs", webhookPayloads.includes("Forge Webhook Payloads") && webhookPayloads.includes("photography_videography") && webhookPayloads.includes("northstar") && webhookPayloads.includes("forge-flex") && webhookPayloads.includes("personal-driver-request") && webhookPayloads.includes("forge-merchant-services") && webhookPayloads.includes("local-product-vendor") && webhookPayloads.includes("vehicle-seller") && webhookPayloads.includes("forge-academy") && webhookPayloads.includes("trade-pathway") && webhookPayloads.includes("employer-training-partner") && webhookPayloads.includes("school-program-partner") && webhookPayloads.includes("resume-request") && webhookPayloads.includes("Public Beta Safety")],
  ["admin auth plan", adminAuthPlan.includes("Forge Admin Auth Plan") && adminAuthPlan.includes("Minimum Public Beta Rule")],
  ["security check script", securityCheck.includes("Forge security check passed.") && securityCheck.includes("fresh cache version")],
  ["public beta deploy runbook", deployRunbook.includes("Forge Public Beta Deploy Runbook") && deployRunbook.includes("Stop Conditions")],
  ["release manifest", releaseManifest.includes("Forge Public Beta Release Candidate") && releaseManifest.includes("\"version\": \"v133\"") && releaseManifest.includes("/request-help?v=133") && releaseManifest.includes("/post-job?v=133") && releaseManifest.includes("/worker-signup?v=133") && releaseManifest.includes("/business?v=133") && releaseManifest.includes("/financial-readiness/") && releaseManifest.includes("/photography?v=133") && releaseManifest.includes("/photography/request?v=133") && releaseManifest.includes("/photography/apply?v=133") && releaseManifest.includes("/photography-videography?v=133") && releaseManifest.includes("/northstar-creative?v=133") && releaseManifest.includes("/forge/capital?v=133") && releaseManifest.includes("/forge/flex?v=133") && releaseManifest.includes("/partners/flex?v=133") && releaseManifest.includes("/personal-driver?v=133") && releaseManifest.includes("/forge-payments?v=133") && releaseManifest.includes("/local-products?v=133") && releaseManifest.includes("/building?v=133") && releaseManifest.includes("/admin/building-leads?v=133") && releaseManifest.includes("/forge-academy?v=133") && releaseManifest.includes("/trade-pathways?v=133") && releaseManifest.includes("/admin/forge-academy?v=133")],
  ["service worker public navigation strategy", serviceWorker.includes('request.mode === "navigate"') && serviceWorker.includes("networkFirstNavigation") && serviceWorker.includes("OFFLINE_URL")],
  ["service worker excludes private routes", serviceWorker.includes("PRIVATE_ROUTE_PATTERN") && serviceWorker.includes("isPrivateRoute(url)") && serviceWorker.includes("api|admin|capture|reports|monetization-admin")],
  ["service worker versioned static assets", serviceWorker.includes("isCurrentStaticAsset") && serviceWorker.includes("styles.css") && serviceWorker.includes("app.js")],
  ["academy route aliases", forgeAcademyRoute.includes("route-loader.js") && forgeAcademyApplyRoute.includes("route-loader.js") && forgeAcademyEmployersRoute.includes("route-loader.js") && forgeAcademySchoolsRoute.includes("route-loader.js") && forgeCareerDashboardRoute.includes("route-loader.js")],
  ["admitly route aliases", admitlyTradePathwaysRoute.includes("route-loader.js") && admitlyTradePathwaysApplyRoute.includes("route-loader.js") && admitlyTradePathwaysDashboardRoute.includes("route-loader.js") && adminForgeAcademyRoute.includes("route-loader.js") && adminTradePathwaysRoute.includes("route-loader.js")],
  ["academy docs", admitlyTradePathwaysDoc.includes("Admitly Trade Pathways") && forgeAcademyDoc.includes("Forge Academy") && admitlyForgeBridgeDoc.includes("Brand Separation") && forgeCareerPlusDoc.includes("Forge Career+")],
  ["release candidate notes", releaseCandidate.includes("Forge Public Beta Release Candidate") && releaseCandidate.includes("Human Gates Still Required")],
  ["release check script", releaseCheck.includes("Forge release check passed.") && releaseCheck.includes("service worker version")],
  ["package scripts", packageJson.includes("\"check\"") && packageJson.includes("check:release")],
  ["github checks workflow", githubWorkflow.includes("Forge Checks") && githubWorkflow.includes("npm run check")],
  ["final public gate", finalPublicGate.includes("Forge Final Public Gate") && finalPublicGate.includes("Launch Decision")],
  ["auto dealer integration", autoDealerIntegration.includes("Forge Auto Dealer Integration") && autoDealerIntegration.includes("JoCo Auto Sales")],
  ["request help route alias", requestHelpRoute.includes("Forge Request Help") && requestHelpRoute.includes("/route-loader.js")],
  ["post job route alias", postJobRoute.includes("Forge Post a Job") && postJobRoute.includes("/route-loader.js")],
  ["worker signup route alias", workerSignupRoute.includes("Forge Worker Signup") && workerSignupRoute.includes("/route-loader.js")],
  ["business help route alias", businessRoute.includes("Forge Business Help") && businessRoute.includes("/route-loader.js")],
  ["financial readiness route", financialReadinessRoute.includes("Forge Financial Readiness") && financialReadinessRoute.includes("/financial-readiness/financial-readiness.css?v=133") && financialReadinessRoute.includes("Public financial-document intake is not open") && financialReadinessRoute.includes("Forge does not currently sell or perform credit-repair services") && !financialReadinessRoute.includes("/route-loader.js")],
  ["financial readiness styles", financialReadinessStyles.includes(".service-grid") && financialReadinessStyles.includes(".status-card")],
  ["photography route", photographyRoute.includes("Forge Photography & Videography") && photographyRoute.includes("/route-loader.js")],
  ["photography request route", photographyRequestRoute.includes("Forge Photography & Videography Request") && photographyRequestRoute.includes("/route-loader.js")],
  ["photography apply route", photographyApplyRoute.includes("Forge Photography & Videography Provider Application") && photographyApplyRoute.includes("/route-loader.js")],
  ["photography videography alias route", creativeRoute.includes("Forge Photography & Videography") && creativeRoute.includes("/route-loader.js")],
  ["northstar creative route", northstarRoute.includes("Forge NorthStar Creative Co.") && northstarRoute.includes("/route-loader.js")],
  ["forge capital route", forgeCapitalRoute.includes("Forge Capital Desk") && forgeCapitalRoute.includes("/route-loader.js")],
  ["forge flex route", forgeFlexRoute.includes("Flex Concept Inactive") && forgeFlexRoute.includes("/route-loader.js")],
  ["partners flex route", partnersFlexRoute.includes("Flex Concept Inactive") && partnersFlexRoute.includes("/route-loader.js")],
  ["personal driver route", personalDriverRoute.includes("Forge Personal Driver") && personalDriverRoute.includes("/route-loader.js")],
  ["private driver route", privateDriverRoute.includes("Forge Private Driver") && privateDriverRoute.includes("/route-loader.js")],
  ["forge payments route", forgePaymentsRoute.includes("Forge Payments") && forgePaymentsRoute.includes("/route-loader.js")],
  ["merchant services route", merchantServicesRoute.includes("Forge Merchant Services") && merchantServicesRoute.includes("/route-loader.js")],
  ["local products route", localProductsRoute.includes("Forge Local Products") && localProductsRoute.includes("/route-loader.js")],
  ["makers route", makersRoute.includes("Forge Makers") && makersRoute.includes("/route-loader.js")],
  ["building route", buildingRoute.includes("Forge Building") && buildingRoute.includes("/route-loader.js")],
  ["admin building route", adminBuildingRoute.includes("Forge Building Leads Admin") && adminBuildingRoute.includes("/route-loader.js")],
  ["flex lead migration", flexMigration.includes("public.forge_flex_leads") && flexMigration.includes("interested_in_forge_job_leads") && flexMigration.includes("interested_in_website_crm_automation") && flexMigration.includes("consent_to_receive_flex_referral") && flexMigration.includes("status in")],
  ["flex docs", flexReadme.includes("Forge Capital Desk") && flexReadme.includes("NEXT_PUBLIC_FLEX_REFERRAL_URL") && flexOutreach.includes("Capital Desk Follow-Up Reference") && flexOutreach.includes("Future-only gate")],
  ["flex api route", flexApiRoute.includes("FORGE_GHL_WEBHOOK_URL") && flexApiRoute.includes("FORGE_ZAPIER_WEBHOOK_URL") && flexApiRoute.includes("forbiddenFieldPattern") && flexApiRoute.includes("FLEX_REFERRAL_AGREEMENT_SIGNED") && flexApiRoute.includes("FLEX_OPERATOR_APPROVED") && flexApiRoute.includes("FLEX_LEGAL_APPROVED") && flexApiEntrypoint.includes('from "./flex-leads/route.js"') && flexApiEntrypoint.includes("export default async function handler")],
  ["flex env example", envExample.includes('NEXT_PUBLIC_FLEX_REFERRAL_URL=""') && envExample.includes("FLEX_APP_URL") && envExample.includes('FLEX_PARTNER_MODE="draft"') && envExample.includes('FLEX_PARTNER_APPROVED="false"') && envExample.includes('FLEX_OPERATOR_APPROVED="false"') && envExample.includes('FLEX_LEGAL_APPROVED="false"') && envExample.includes("FORGE_CAPITAL_DESK_ENABLED")]
].filter(([, ok]) => !ok).map(([label]) => label);
const darkThemeLeak = /#09090b|color-scheme:\s*dark|industrial/i.test(css);

if (missingHtml.length || missingJs.length || missingCss.length || missingPwa.length || missingDeploy.length || missingTradeLabels.length || missingTradeHooks.length || darkThemeLeak) {
  console.error("Forge smoke test failed.");
  if (missingHtml.length) console.error("Missing HTML:", missingHtml.join(", "));
  if (missingJs.length) console.error("Missing JS:", missingJs.join(", "));
  if (missingCss.length) console.error("Missing CSS:", missingCss.join(", "));
  if (missingPwa.length) console.error("Missing PWA:", missingPwa.join(", "));
  if (missingDeploy.length) console.error("Missing Deploy:", missingDeploy.join(", "));
  if (missingTradeLabels.length) console.error("Missing trade categories:", missingTradeLabels.join(", "));
  if (missingTradeHooks.length) console.error("Missing trade hooks:", missingTradeHooks.join(", "));
  if (darkThemeLeak) console.error("Found a dark-theme marker in styles.css");
  process.exit(1);
}

console.log("Forge smoke test passed.");
