import { readFile } from "node:fs/promises";

const requiredHtml = [
  "Post the job.",
  "I need workers",
  "I need work",
  "Forge Confirmation",
  "confirmNextSteps",
  "confirmHandoff",
  "Copy Handoff",
  "Lead Capture Setup",
  "Lead Delivery Status",
  "deliveryStatus",
  "Copy Status",
  "Backend Handoff",
  "backendHandoff",
  "Copy Backend Handoff",
  "Admin Auth Handoff",
  "authHandoff",
  "Copy Auth Handoff",
  "Worker Leads",
  "Export Workers CSV",
  "Copy Daily Brief",
  "Activity Log",
  "First 200 launch",
  "Early user pipeline",
  "Copy Launch Invite",
  "What happens next",
  "Every early signup turns into a clear follow-up.",
  "Can people sign up?",
  "Yes: start with a controlled first-user group.",
  "Safe to collect today",
  "Copy Signup Checklist",
  "Early Access Terms & Privacy",
  "Forge is a controlled beta MVP.",
  "Terms & Privacy",
  "Forge Auto Services",
  "Buy. Sell. Repair. Transport.",
  "vehicleListingForm",
  "Track Your Home From Dirt to Done",
  "Forge Build Tracker",
  "homebuildingFeatureGrid",
  "buildTrackerDashboard",
  "Sample data only",
  "Training & Careers",
  "Apply to trade schools, unions, and blue-collar AI jobs.",
  "opportunityForm",
  "opportunityStats",
  "opportunityTrackGrid",
  "Copy Application Plan",
  "Copy Career Leads",
  "Save Career Interest",
  "Copy Auto Brief",
  "Dealer network",
  "Dealer setup checklist",
  "Copy Setup Checklist",
  "autoDealerSetup",
  "Copy Dealer Plan",
  "autoDealerGrid",
  "Dealer Partner",
  "Buyer inquiries",
  "autoInquiryForm",
  "autoInquiryList",
  "Copy Buyer Queue",
  "Auto safety",
  "Photography & Videography",
  "Hire Local Photographers & Videographers",
  "creativeLeadForm",
  "creativeProviderForm",
  "Book a Creative",
  "Apply as a Provider",
  "Forge helps customers connect with trusted local creatives, including photographers and videographers like Dennis and other approved providers in the community.",
  "Start here",
  "Choose the path that matches why you came to Forge.",
  "startPathGrid",
  "Copy First User Links",
  "Quick Capture",
  "Save the lead before the moment passes.",
  "Referral / Friend Leads",
  "Follow-Up Queue",
  "Public View",
  "Import Backup",
  "Submit a Bid",
  "Bid Activity",
  "My Job Status",
  "Status privacy",
  "No payment or account password is required.",
  "Demo script",
  "Log in to Forge",
  "Mike Jones",
  "Forge Admin",
  "Forge Messages",
  "Active conversations",
  "messageSummary",
  "Save as Sent",
  "Forge Reports",
  "MVP traction report",
  "Profile Status",
  "profileReadiness",
  "Status brief",
  "Copy Status Brief",
  "profileBrief",
  "Status checklist",
  "Ready for bids",
  "Operator active",
  "Perspective Demo",
  "Show people their side",
  "3-minute walkthrough",
  "Live demo cue cards",
  "demoCueGrid",
  "Best demo path",
  "Shareable links",
  "Copy Demo Script",
  "After the demo",
  "Turn interest into one clear next step.",
  "MVP ready today",
  "Final demo checklist",
  "Copy Demo Pack",
  "Copy Close Ask",
  "Follow-up consent",
  "No payment is collected in this MVP.",
  "Worker follow-up",
  "Open demo paths",
  "Open profile status",
  "Safety Center",
  "Check the MVP before real outreach.",
  "Copy Launch Gate",
  "Public Deploy Preflight",
  "publicReadinessScore",
  "Copy RC Packet",
  "Copy Runbook",
  "Copy Check Command",
  "Copy Final Gate",
  "Copy Deploy Plan",
  "Copy Security Review",
  "deployChecklist",
  "launchGate",
  "safetyChecklist",
  "Launch Command",
  "Who needs action today?",
  "launchCommandCenter",
  "Outreach Recap",
  "What moved today?",
  "outreachRecap",
  "Next 10 Batch",
  "Run one focused outreach sprint.",
  "outreachBatch",
  "Complete Sprint",
  "Session History",
  "Recent outreach sprints.",
  "sessionHistory",
  "styles.css?v=70",
  "app.js?v=70"
];

const requiredJs = [
  "forge.wireframe.mvp.v1",
  "sendLead",
  "exportCsv",
  "exportBackup",
  "copyDailyBrief",
  "foundingSegments",
  "renderFounding200",
  "copyFirst200Plan",
  "quickLeadForm",
  "referrals",
  "markReferralContacted",
  "togglePublicMode",
  "importBackup",
  "copyFollowUpQueue",
  "queue-next",
  "queue-rank",
  "followUpProgress",
  "renderFollowUpProgress",
  "todayFollowUp",
  "renderTodayFollowUp",
  "filteredFollowUpRows",
  "followUpScore",
  "followUpReason",
  "bidForm",
  "jobFlowTracker",
  "jobFlowSteps",
  "jobFlowBrief",
  "jobFlowBriefRows",
  "copyJobFlowBrief",
  "Forge job flow brief",
  "Job-to-bid flow",
  "Copy Flow Brief",
  "Where this job stands now",
  "Message / schedule",
  "adminBidsTable",
  "statusLookupForm",
  "renderStatusResults",
  "statusEmptyState",
  "Forge did not find a job for that contact.",
  "renderDemoSteps",
  "startPaths",
  "renderStartPaths",
  "copyFirstUserLinks",
  "Forge first-user links",
  "copySignupChecklist",
  "Forge first-user signup checklist",
  "Post one real job.",
  "copyInviteText",
  "vehicles",
  "autoServiceGroups",
  "autoServiceOptions",
  "autoRequests",
  "autoDealers",
  "renderAutos",
  "autoDealerName",
  "copyAutoDealerPlan",
  "copyAutoDealerSetup",
  "copyAutoDealer",
  "JoCo Auto Sales",
  "Chevelles Auto Sales",
  "Shasta Lake Auto Sales",
  "S&A Auto",
  "copyAutoServiceRequest",
  "copyAutoServiceQueue",
  "Forge Auto service request",
  "copyAutoMarketBrief",
  "copyVehicleContact",
  "autoInquiries",
  "copyAutoInquiry",
  "copyAutoInquiryQueue",
  "autoInquiryLines",
  "Forge auto buyer inquiry",
  "Forge Auto Services brief",
  "Vehicle listing saved.",
  "Copy Seller Info",
  "CREATIVE_CATEGORY_VALUE",
  "photography_videography",
  "creativeServiceTypes",
  "renderCreativePage",
  "submitCreativeLead",
  "submitCreativeProvider",
  "copyCreativeBrief",
  "copyCreativeQueue",
  "Forge creative lead",
  "Forge creative provider application",
  "BuildTrackerDashboard",
  "ProjectSummaryCard",
  "GanttTimeline",
  "BudgetDashboard",
  "ExpenseReportTable",
  "ProjectTeamCard",
  "ChangeOrderCard",
  "DocumentVaultCard",
  "LatestUpdatesCard",
  "Sample Custom Home Build",
  "opportunityTracks",
  "opportunitySteps",
  "opportunityLeads",
  "renderOpportunities",
  "copyOpportunityPlan",
  "copyOpportunityLead",
  "copyOpportunityLeads",
  "opportunityLeadText",
  "opportunityLeadLines",
  "markOpportunityContacted",
  "moveOpportunityForward",
  "Forge opportunity application plan",
  "Forge career opportunity lead",
  "Trade school",
  "Union / apprenticeship",
  "Blue-collar AI jobs",
  "Career interest saved.",
  "markJobContacted",
  "moveJobForward",
  "moveWorkerForward",
  "moveReferralForward",
  "move-job-forward",
  "adminWorkersTable",
  "webhookUrl",
  "renderDeliveryStatus",
  "deliveryStatusRows",
  "copyDeliveryStatus",
  "updateWebhookDelivery",
  "renderBackendHandoff",
  "backendHandoffRows",
  "copyBackendHandoff",
  "Supabase schema prepared",
  "renderAuthHandoff",
  "authHandoffRows",
  "copyAuthHandoff",
  "Browser-only demo state is not production auth",
  "demoAccounts",
  "loginAs",
  "renderSession",
  "Log in as Forge Admin to open operator tools.",
  "expireAdminSession",
  "syncWorkerSession",
  "renderMessages",
  "messageSummary",
  "messageContext",
  "saveMessageDraft",
  "loadCustomerStatus",
  "renderReports",
  "confirmNextSteps",
  "confirmationHandoffTitle",
  "confirmationHandoffText",
  "copyConfirmationHandoff",
  "Confirmation handoff copied.",
  "Forge saves this job to the local Admin queue",
  "reportItem",
  "renderProfileStatus",
  "getProfileStatus",
  "readinessCard",
  "profileReadiness",
  "profileBriefRows",
  "copyProfileBrief",
  "Forge profile status brief",
  "workerProfileStatus",
  "customerProfileStatus",
  "perspectiveCards",
  "renderPerspective",
  "demoGuide",
  "renderDemoGuide",
  "demoCueCards",
  "renderDemoCueCards",
  "copyDemoCue",
  "Copy Cue",
  "You should be able to see what is happening with your job",
  "demoPaths",
  "renderDemoPath",
  "renderDemoLinks",
  "customerDemoJobPriority",
  "Homeowner proof",
  "Forge Auto services proof",
  "Auto buyer / seller",
  "Forge Auto can capture vehicle service",
  "autoLeadRouteRows",
  "Soft launch route",
  "Forge Auto Services:",
  "renderDemoOutcomes",
  "renderNavigationState",
  "renderFinishChecklist",
  "copyDemoScript",
  "copyDemoPack",
  "copyDemoLink",
  "copyCloseAsk",
  "renderSafetyCenter",
  "renderSoftLaunchPlan",
  "softLaunchRows",
  "renderSoftLaunchInvites",
  "softLaunchInviteRows",
  "renderSoftLaunchRunSheet",
  "softLaunchRunSheetRows",
  "copySoftLaunchPlan",
  "copySoftLaunchInvite",
  "copySoftLaunchInviteKit",
  "copySoftLaunchRunSheet",
  "Forge soft launch tomorrow plan",
  "Forge soft launch invite kit",
  "Forge launch day run sheet",
  "Controlled soft launch only",
  "launchGateRows",
  "Ready for controlled signups",
  "Do not send broadly yet",
  "copyLaunchGate",
  "deployPreflightRows",
  "publicReadinessSummary",
  "publicReadinessBlockers",
  "Public beta readiness",
  "finalSecurityGate",
  "Static host security config",
  "Lead capture backend",
  "Client admin gate",
  "copyDeployPlan",
  "copyReleaseCandidatePacket",
  "Forge public beta release candidate packet",
  "copyLaunchRunbook",
  "Forge public beta deploy runbook",
  "copySecurityCommand",
  "npm run check",
  "copyFinalSecurityGate",
  "finalSecurityGateRows",
  "Forge final public gate",
  "copySecurityReviewPack",
  "Forge final public security review",
  "safetyChecks",
  "copySafetyChecklist",
  "lastBackupLeadCount",
  "renderLaunchCommandCenter",
  "launchCommandRows",
  "copyLaunchCommand",
  "renderOutreachRecap",
  "outreachRecapSummary",
  "copyOutreachRecap",
  "renderOutreachBatch",
  "outreachBatchRows",
  "copyOutreachBatch",
  "completeOutreachSprint",
  "Outreach sprint completed",
  "renderSessionHistory",
  "outreachSessionHistory",
  "copySessionHistory",
  "copySessionNote",
  "Selected bid handoff",
  "chosenBidHandoff",
  "bidHandoffText",
  "copyBidHandoff",
  "closeAskText",
  "roleDemoLink",
  "copyPerspectiveLink",
  "perspectiveLink",
  "copy-perspective-link",
  "demo=",
  "Bid chosen.",
  "View as"
];

const html = await readFile("index.html", "utf8");
const js = await readFile("app.js", "utf8");
const css = await readFile("styles.css", "utf8");
const manifest = await readFile("manifest.webmanifest", "utf8");
const serviceWorker = await readFile("service-worker.js", "utf8");
const netlify = await readFile("netlify.toml", "utf8");
const vercel = await readFile("vercel.json", "utf8");
const robots = await readFile("robots.txt", "utf8");
const securityReview = await readFile("SECURITY_REVIEW_CHECKLIST.md", "utf8");
const supabaseSchema = await readFile("SUPABASE_SCHEMA.sql", "utf8");
const webhookPayloads = await readFile("WEBHOOK_PAYLOADS.md", "utf8");
const adminAuthPlan = await readFile("ADMIN_AUTH_PLAN.md", "utf8");
const securityCheck = await readFile("security-check.mjs", "utf8");
const deployRunbook = await readFile("PUBLIC_BETA_DEPLOY_RUNBOOK.md", "utf8");
const releaseManifest = await readFile("release-manifest.json", "utf8");
const releaseCandidate = await readFile("RELEASE_CANDIDATE.md", "utf8");
const releaseCheck = await readFile("release-check.mjs", "utf8");
const packageJson = await readFile("package.json", "utf8");
const githubWorkflow = await readFile(".github/workflows/forge-checks.yml", "utf8");
const finalPublicGate = await readFile("FINAL_PUBLIC_GATE.md", "utf8");
const autoDealerIntegration = await readFile("AUTO_DEALER_INTEGRATION.md", "utf8");
const creativeRoute = await readFile("photography-videography/index.html", "utf8");

const missingHtml = requiredHtml.filter((text) => !html.includes(text));
const missingJs = requiredJs.filter((text) => !js.includes(text));
const missingCss = [
  ["safe-area mobile tabbar", css.includes("env(safe-area-inset-bottom)")],
  ["compact phone feature strip", css.includes(".feature-strip") && css.includes("repeat(3, minmax(0, 1fr))")],
  ["auto services", css.includes(".auto-layout") && css.includes(".auto-card") && css.includes(".auto-sell-card") && css.includes(".auto-service-grid")],
  ["auto service requests", css.includes(".auto-request-section") && css.includes(".auto-request-list") && css.includes(".auto-service-form")],
  ["auto dealer network", css.includes(".auto-dealer-grid") && css.includes(".auto-dealers")],
  ["auto dealer setup", css.includes(".auto-setup-grid") && css.includes(".auto-setup")],
  ["auto buyer inquiries", css.includes(".auto-inquiries") && css.includes(".auto-inquiry-list")],
  ["auto lead route", css.includes(".auto-route-grid") && css.includes(".auto-route")],
  ["photography videography page", css.includes(".creative-layout") && css.includes(".creative-service-grid") && css.includes(".creative-provider-panel")],
  ["homebuilding page", css.includes(".homebuilding-layout") && css.includes(".tracker-feature-card")],
  ["build tracker dashboard", css.includes(".build-tracker-dashboard") && css.includes(".tracker-card")],
  ["build tracker gantt", css.includes(".gantt-scroll") && css.includes(".gantt-bar")],
  ["build tracker budget", css.includes(".budget-category-grid") && css.includes(".budget-alerts")],
  ["training careers hub", css.includes(".opportunity-layout") && css.includes(".opportunity-track-grid") && css.includes(".opportunity-lead-list")],
  ["soft launch plan", css.includes(".soft-launch-grid") && css.includes(".soft-launch")],
  ["first user start path", css.includes(".start-path-grid") && css.includes(".start-path-card")],
  ["first user path heading", css.includes(".start-path-heading")],
  ["signup readiness panel", css.includes(".signup-readiness-panel") && css.includes(".readiness-grid")],
  ["launch gate panel", css.includes(".launch-gate") && css.includes(".launch-gate-card.blocked")],
  ["deploy preflight panel", css.includes(".deploy-preflight") && css.includes(".deploy-grid")],
  ["readiness score panel", css.includes(".readiness-score") && css.includes(".readiness-score h3")],
  ["profile brief panel", css.includes(".profile-brief-grid") && css.includes(".profile-brief-heading")],
  ["final gate panel", css.includes(".final-gate") && css.includes(".final-gate article.hold")],
  ["delivery status panel", css.includes(".delivery-status") && css.includes(".delivery-grid")],
  ["backend handoff panel", css.includes(".backend-handoff") && css.includes(".backend-grid")],
  ["auth handoff panel", css.includes(".auth-handoff") && css.includes(".auth-grid")],
  ["legal screen", css.includes(".legal-layout") && css.includes(".legal-grid")],
  ["confirmation next steps", css.includes(".confirm-next") && css.includes(".confirm-next article")],
  ["confirmation handoff", css.includes(".confirm-handoff") && css.includes("border-left: 6px solid var(--orange)")],
  ["job flow tracker", css.includes(".job-flow-grid") && css.includes(".job-flow-grid article.active")],
  ["job flow brief", css.includes(".job-flow-brief-grid") && css.includes(".job-flow-brief-heading")],
  ["status empty guidance", css.includes(".status-empty")],
  ["admin safety grid", css.includes(".safety-grid") && css.includes(".safety-item.attention")],
  ["launch command cards", css.includes(".launch-command-grid") && css.includes(".command-meter")],
  ["outreach recap grid", css.includes(".outreach-recap-grid") && css.includes(".recap-list")],
  ["next 10 outreach batch", css.includes(".next-batch-list") && css.includes(".batch-row")],
  ["compact action buttons", css.includes(".compact-actions")],
  ["session history cards", css.includes(".session-history-list") && css.includes(".session-card")],
  ["selected bid handoff card", css.includes(".handoff-card") && css.includes(".handoff-grid")]
].filter(([, ok]) => !ok).map(([label]) => label);
const missingPwa = [
  ["manifest link", html.includes("manifest.webmanifest")],
  ["service worker registration", js.includes("registerServiceWorker")],
  ["manifest name", manifest.includes("Forge MVP")],
  ["service worker cache", serviceWorker.includes("CACHE_NAME")],
  ["fresh service worker cache", serviceWorker.includes("forge-mvp-v70")]
].filter(([, ok]) => !ok).map(([label]) => label);
const missingDeploy = [
  ["netlify security headers", netlify.includes("Content-Security-Policy") && netlify.includes("X-Frame-Options")],
  ["netlify spa redirect", netlify.includes("[[redirects]]") && netlify.includes("/index.html")],
  ["vercel security headers", vercel.includes("Content-Security-Policy") && vercel.includes("Permissions-Policy")],
  ["vercel rewrite", vercel.includes("\"rewrites\"") && vercel.includes("\"/index.html\"")],
  ["robots present", robots.includes("User-agent: *")],
  ["security review checklist", securityReview.includes("Forge Security Review Checklist") && securityReview.includes("Launch Decision")],
  ["supabase schema", supabaseSchema.includes("forge_job_leads") && supabaseSchema.includes("forge_opportunity_leads") && supabaseSchema.includes("photography_videography") && supabaseSchema.includes("enable row level security")],
  ["webhook payload docs", webhookPayloads.includes("Forge Webhook Payloads") && webhookPayloads.includes("opportunity") && webhookPayloads.includes("Public Beta Safety")],
  ["admin auth plan", adminAuthPlan.includes("Forge Admin Auth Plan") && adminAuthPlan.includes("Minimum Public Beta Rule")],
  ["security check script", securityCheck.includes("Forge security check passed.") && securityCheck.includes("fresh cache version")],
  ["public beta deploy runbook", deployRunbook.includes("Forge Public Beta Deploy Runbook") && deployRunbook.includes("Stop Conditions")],
  ["release manifest", releaseManifest.includes("Forge Public Beta Release Candidate") && releaseManifest.includes("\"version\": \"v70\"") && releaseManifest.includes("/photography-videography?v=70")],
  ["release candidate notes", releaseCandidate.includes("Forge Public Beta Release Candidate") && releaseCandidate.includes("Human Gates Still Required")],
  ["release check script", releaseCheck.includes("Forge release check passed.") && releaseCheck.includes("service worker version")],
  ["package scripts", packageJson.includes("\"check\"") && packageJson.includes("check:release")],
  ["github checks workflow", githubWorkflow.includes("Forge Checks") && githubWorkflow.includes("npm run check")],
  ["final public gate", finalPublicGate.includes("Forge Final Public Gate") && finalPublicGate.includes("Launch Decision")],
  ["auto dealer integration", autoDealerIntegration.includes("Forge Auto Dealer Integration") && autoDealerIntegration.includes("JoCo Auto Sales")],
  ["photography videography route", creativeRoute.includes("Forge Photography & Videography") && creativeRoute.includes("/route-loader.js")]
].filter(([, ok]) => !ok).map(([label]) => label);
const darkThemeLeak = /#09090b|color-scheme:\s*dark|industrial/i.test(css);

if (missingHtml.length || missingJs.length || missingCss.length || missingPwa.length || missingDeploy.length || darkThemeLeak) {
  console.error("Forge smoke test failed.");
  if (missingHtml.length) console.error("Missing HTML:", missingHtml.join(", "));
  if (missingJs.length) console.error("Missing JS:", missingJs.join(", "));
  if (missingCss.length) console.error("Missing CSS:", missingCss.join(", "));
  if (missingPwa.length) console.error("Missing PWA:", missingPwa.join(", "));
  if (missingDeploy.length) console.error("Missing Deploy:", missingDeploy.join(", "));
  if (darkThemeLeak) console.error("Found a dark-theme marker in styles.css");
  process.exit(1);
}

console.log("Forge smoke test passed.");
