import { readFile } from "node:fs/promises";

const requiredHtml = [
  "Post the job.",
  "I need workers",
  "I need work",
  "Forge Confirmation",
  "confirmNextSteps",
  "confirmHandoff",
  "Copy Handoff",
  "Lead Capture Setup",
  "Lead Delivery Status",
  "deliveryStatus",
  "Copy Status",
  "Backend Handoff",
  "backendHandoff",
  "Copy Backend Handoff",
  "Admin Auth Handoff",
  "authHandoff",
  "Copy Auth Handoff",
  "Worker Leads",
  "Export Workers CSV",
  "Copy Daily Brief",
  "Activity Log",
  "First 200 launch",
  "Early user pipeline",
  "Copy Launch Invite",
  "What happens next",
  "Every early signup turns into a clear follow-up.",
  "Can people sign up?",
  "Yes: start with a controlled first-user group.",
  "Safe to collect today",
  "Copy Signup Checklist",
  "Forge Launch Status",
  "Soft launch readiness",
  "Forge is ready for controlled first-user demos, not broad public traffic yet.",
  "Recommended soft-launch path",
  "No live payments",
  "Backend required",
  "Security gate required",
  "Early Access Terms & Privacy",
  "Forge is a controlled beta MVP.",
  "Terms & Privacy",
  "Forge Auto Services",
  "Forge Auto & Transport",
  "Buy. Sell. Repair. Transport.",
  "Sell My Car on Forge",
  "Forge Platinum Auto Concierge",
  "Premium vehicle sourcing, selling, consignment, and white-glove transport.",
  "vehicleListingForm",
  "vehicleSellingPath",
  "vehiclePartnerConsent",
  "Track Your Home From Dirt to Done",
  "Forge Build Tracker",
  "homebuildingFeatureGrid",
  "buildTrackerDashboard",
  "Sample data only",
  "Training & Careers",
  "Apply to trade schools, unions, and blue-collar AI jobs.",
  "opportunityForm",
  "opportunityStats",
  "opportunityTrackGrid",
  "Copy Application Plan",
  "Copy Career Leads",
  "Save Career Interest",
  "Forge Academy",
  "Blue-collar career pathways, trade-school help, apprenticeships, resumes, and local job placement powered by Admitly.",
  "forgeAcademyStudentForm",
  "academyOptionGrid",
  "careerPlusFeatureGrid",
  "Save Career Intake",
  "Employer / contractor partner",
  "academyEmployerForm",
  "School / program partner",
  "academySchoolForm",
  "Admitly Trade Pathways",
  "Your Future. Admitted.",
  "admitlyTradePathwayForm",
  "admitlyPathwayGrid",
  "admitlyDashboardGrid",
  "Save Trade Pathway Lead",
  "adminForgeAcademyTable",
  "adminTradePathwaysTable",
  "Copy Academy Queue",
  "Copy Auto Brief",
  "Dealer network",
  "Dealer setup checklist",
  "Copy Setup Checklist",
  "autoDealerSetup",
  "Copy Dealer Plan",
  "autoDealerGrid",
  "Dealer Partner",
  "Buyer inquiries",
  "autoInquiryForm",
  "autoInquiryList",
  "Copy Buyer Queue",
  "Auto safety",
  "Forge Road Rescue",
  "Emergency? Call 911 first.",
  "Pothole Impact Help",
  "roadRescueForm",
  "Road Rescue Leads",
  "Export Road Rescue CSV",
  "Report the Pothole",
  "Photography & Videography",
  "Hire a Photographer",
  "Request a Shoot",
  "Apply as a Photographer",
  "creativeLeadForm",
  "creativeProviderForm",
  "creativeDeliveryDeadline",
  "creativeProviderEditingSoftware",
  "Photography & Videography Booking Notes",
  "Built for trust and quality.",
  "Forge helps customers connect with trusted local creatives, including photographers, videographers, and approved local creative providers in the community.",
  "NorthStar Creative Co.",
  "Grow Your Business with North Star Creative Co.",
  "Forge helps you find work. North Star Creative Co. helps your business win more of it.",
  "Grow My Business",
  "Request a Free Marketing Audit",
  "northstarLeadForm",
  "northstarServices",
  "northstarBudget",
  "adminNorthstarTable",
  "adminNorthstarPipeline",
  "Forge Capital Desk",
  "Business owners need breathing room.",
  "discover modern business finance tools through our Flex referral channel.",
  "Forge Capital Desk Lead Form",
  "Continue to Flex",
  "flexLeadForm",
  "flexConsentToContact",
  "flexConsentReferral",
  "flexInterestedWebsiteCrm",
  "Personal Driver / Private Driver Services",
  "personalDriverRequestForm",
  "personalDriverProviderForm",
  "adminPersonalDriverRequestsTable",
  "adminPersonalDriverProvidersTable",
  "Forge Payments / Merchant Services",
  "merchantServicesLeadForm",
  "merchantServicesCompliance",
  "adminMerchantServicesTable",
  "Local Products / Makers",
  "localProductVendorForm",
  "adminLocalProductsTable",
  "Worker Trust / Proof Ledger",
  "Green/Silver/Gold",
  "providerGrowthTools",
  "adminFlexLeadsTable",
  "flex_link_sent",
  "Copy Queue",
  "Talk to Forge Capital Desk",
  "Start here",
  "Choose the path that matches why you came to Forge.",
  "startPathGrid",
  "Copy First User Links",
  "Forge Building",
  "Build smarter. Fund smarter. Finish with trusted operators.",
  "Request Contractor Finance Review",
  "buildingLeadForm",
  "adminBuildingFullTable",
  "adminBuildingFullPipeline",
  "Quick Capture",
  "Save the lead before the moment passes.",
  "Referral / Friend Leads",
  "Follow-Up Queue",
  "Public View",
  "Import Backup",
  "Submit a Bid",
  "Bid Activity",
  "My Job Status",
  "Status privacy",
  "No payment or account password is required.",
  "Demo script",
  "Log in to Forge",
  "Mike Jones",
  "Forge Admin",
  "Forge Messages",
  "Active conversations",
  "messageSummary",
  "Save as Sent",
  "Forge Reports",
  "MVP traction report",
  "Profile Status",
  "profileReadiness",
  "Status brief",
  "Copy Status Brief",
  "profileBrief",
  "Status checklist",
  "Ready for bids",
  "Operator active",
  "Perspective Demo",
  "Show people their side",
  "3-minute walkthrough",
  "Live demo cue cards",
  "demoCueGrid",
  "Best demo path",
  "Shareable links",
  "Copy Demo Script",
  "After the demo",
  "Turn interest into one clear next step.",
  "MVP ready today",
  "Final demo checklist",
  "Copy Demo Pack",
  "Copy Close Ask",
  "Follow-up consent",
  "No payment is collected in this MVP.",
  "Worker follow-up",
  "Open demo paths",
  "Open profile status",
  "Safety Center",
  "Check the MVP before real outreach.",
  "Copy Launch Gate",
  "Public Deploy Preflight",
  "publicReadinessScore",
  "Copy RC Packet",
  "Copy Runbook",
  "Copy Check Command",
  "Copy Final Gate",
  "Copy Deploy Plan",
  "Copy Security Review",
  "deployChecklist",
  "launchGate",
  "safetyChecklist",
  "Launch Command",
  "Who needs action today?",
  "launchCommandCenter",
  "Outreach Recap",
  "What moved today?",
  "outreachRecap",
  "Next 10 Batch",
  "Run one focused outreach sprint.",
  "outreachBatch",
  "Complete Sprint",
  "Session History",
  "Recent outreach sprints.",
  "sessionHistory",
  "styles.css?v=71",
  "app.js?v=71"
];

const requiredJs = [
  "forge.wireframe.mvp.v1",
  "sendLead",
  "exportCsv",
  "exportBackup",
  "copyDailyBrief",
  "foundingSegments",
  "renderFounding200",
  "copyFirst200Plan",
  "quickLeadForm",
  "referrals",
  "markReferralContacted",
  "togglePublicMode",
  "importBackup",
  "copyFollowUpQueue",
  "queue-next",
  "queue-rank",
  "followUpProgress",
  "renderFollowUpProgress",
  "todayFollowUp",
  "renderTodayFollowUp",
  "filteredFollowUpRows",
  "followUpScore",
  "followUpReason",
  "bidForm",
  "jobFlowTracker",
  "jobFlowSteps",
  "jobFlowBrief",
  "jobFlowBriefRows",
  "copyJobFlowBrief",
  "Forge job flow brief",
  "Job-to-bid flow",
  "Copy Flow Brief",
  "Where this job stands now",
  "Message / schedule",
  "renderForgeAcademy",
  "renderAdmitlyTradePathways",
  "renderAcademyAdmin",
  "copyAcademyBrief",
  "copyAcademyAdminQueue",
  "resumeRequestFromAcademyLead",
  "resumeRequestFromTradePathwayLead",
  "academyConfirmation",
  "tradePathwayLeads",
  "forgeAcademyLeads",
  "adminBidsTable",
  "statusLookupForm",
  "renderStatusResults",
  "statusEmptyState",
  "Forge did not find a job for that contact.",
  "renderDemoSteps",
  "startPaths",
  "renderStartPaths",
  "copyFirstUserLinks",
  "Forge first-user links",
  "copySignupChecklist",
  "Forge first-user signup checklist",
  "Post one real job.",
  "copyInviteText",
  "vehicles",
  "autoServiceGroups",
  "autoTransportServiceCards",
  "autoLeadCategoryLabels",
  "operationsVaultDocuments",
  "autoServiceOptions",
  "autoRequests",
  "autoDealers",
  "renderAutos",
  "autoDealerName",
  "copyAutoDealerPlan",
  "copyAutoDealerSetup",
  "copyAutoDealer",
  "JoCo Auto Sales",
  "Chevelles Auto Sales",
  "Shasta Lake Auto Sales",
  "S&A Auto",
  "copyAutoServiceRequest",
  "copyAutoServiceQueue",
  "Forge Auto service request",
  "copyAutoMarketBrief",
  "copyAutoTransportMenu",
  "renderAutoAdminViews",
  "renderOperationsVault",
  "copyOperationsVaultIndex",
  "copyVehicleContact",
  "vehicleLeadTags",
  "vehicleAssignedPartner",
  "Forge Platinum Auto Concierge",
  "Marc - Portland Luxury Auto Partner",
  "autoInquiries",
  "copyAutoInquiry",
  "copyAutoInquiryQueue",
  "autoInquiryLines",
  "Forge auto buyer inquiry",
  "Forge Auto Services brief",
  "Vehicle seller lead saved.",
  "Copy Seller Info",
  "ROAD_RESCUE_SERVICE_TYPE",
  "road_rescue",
  "roadRescueRequests",
  "renderRoadRescue",
  "copyRoadRescueQueue",
  "roadRescueProviderNotification",
  "Forge Road Rescue received your request.",
  "CREATIVE_CATEGORY_VALUE",
  "CREATIVE_CATEGORY_SLUG",
  "photography_videography",
  "creativeRequestStatuses",
  "creativeProviderStatuses",
  "creativeDeliveryOptions",
  "creativeServiceTypes",
  "creativeProviderDroneCapability",
  "adminCreativeRequestsTable",
  "adminCreativeProvidersTable",
  "renderCreativePage",
  "submitCreativeLead",
  "submitCreativeProvider",
  "copyCreativeBrief",
  "copyCreativeQueue",
  "Forge creative lead",
  "Forge creative provider application",
  "NORTHSTAR_CATEGORY_VALUE",
  "NORTHSTAR_OPERATIONS_CATEGORY_VALUE",
  "northstarMarketingServices",
  "northstarOperationsServices",
  "northstarPackages",
  "northstarStatuses",
  "renderNorthStarPage",
  "renderPersonalDriverPage",
  "renderPaymentsPage",
  "renderLocalProductsPage",
  "workerTrustProfile",
  "workerTrustLedgerHtml",
  "jobSafetyGateHtml",
  "workerTrustTiers",
  "dispatchDecisionLabels",
  "personalDriverRequests",
  "personalDriverProviders",
  "merchantServiceLeads",
  "localProductVendors",
  "submitPersonalDriverRequest",
  "submitPersonalDriverProvider",
  "submitMerchantServicesLead",
  "submitLocalProductVendor",
  "forge-merchant-services",
  "local-product-vendor",
  "submitNorthStarLead",
  "northstarLeadText",
  "northstarLeadLines",
  "copyNorthStarBrief",
  "copyNorthStarQueue",
  "copyNorthStarLead",
  "markNorthStarContacted",
  "moveNorthStarForward",
  "northstar_marketing_operations",
  "flexLeadStatuses",
  "FORGE_CAPITAL_DESK_ENABLED",
  "FLEX_COMPLIANCE_COPY",
  "renderCapitalPage",
  "normalizeFlexLead",
  "calculateFlexLeadScore",
  "submitFlexLead",
  "renderFlexLeadsAdmin",
  "copyFlexBrief",
  "copyFlexQueue",
  "openFlexReferral",
  "createFlexUpsellTask",
  "forge-flex",
  "flex_link_sent",
  "provider_onboarding",
  "BuildTrackerDashboard",
  "ProjectSummaryCard",
  "GanttTimeline",
  "BudgetDashboard",
  "ExpenseReportTable",
  "ProjectTeamCard",
  "ChangeOrderCard",
  "DocumentVaultCard",
  "LatestUpdatesCard",
  "Sample Custom Home Build",
  "opportunityTracks",
  "opportunitySteps",
  "opportunityLeads",
  "renderOpportunities",
  "copyOpportunityPlan",
  "copyOpportunityLead",
  "copyOpportunityLeads",
  "opportunityLeadText",
  "opportunityLeadLines",
  "buildingLeadStatuses",
  "buildingLeadRouting",
  "normalizeBuildingLead",
  "renderBuildingPage",
  "renderAdminBuildingLeadsPage",
  "submitBuildingLead",
  "canSendBuildingToSeneca",
  "canSendBuildingToFlex",
  "copyBuildingQueue",
  "FLEX_APP_URL",
  "BUILDING_COMPLIANCE_COPY",
  "markOpportunityContacted",
  "moveOpportunityForward",
  "Forge opportunity application plan",
  "Forge career opportunity lead",
  "Trade school",
  "Union / apprenticeship",
  "Blue-collar AI jobs",
  "Career interest saved.",
  "markJobContacted",
  "moveJobForward",
  "moveWorkerForward",
  "moveReferralForward",
  "move-job-forward",
  "adminWorkersTable",
  "webhookUrl",
  "renderDeliveryStatus",
  "deliveryStatusRows",
  "copyDeliveryStatus",
  "updateWebhookDelivery",
  "renderBackendHandoff",
  "backendHandoffRows",
  "copyBackendHandoff",
  "Supabase schema prepared",
  "renderAuthHandoff",
  "authHandoffRows",
  "copyAuthHandoff",
  "Browser-only demo state is not production auth",
  "demoAccounts",
  "loginAs",
  "renderSession",
  "Log in as Forge Admin to open operator tools.",
  "expireAdminSession",
  "syncWorkerSession",
  "renderMessages",
  "messageSummary",
  "messageContext",
  "saveMessageDraft",
  "loadCustomerStatus",
  "renderReports",
  "confirmNextSteps",
  "confirmationHandoffTitle",
  "confirmationHandoffText",
  "copyConfirmationHandoff",
  "Confirmation handoff copied.",
  "Forge saves this job to the local Admin queue",
  "reportItem",
  "renderProfileStatus",
  "getProfileStatus",
  "readinessCard",
  "profileReadiness",
  "profileBriefRows",
  "copyProfileBrief",
  "Forge profile status brief",
  "workerProfileStatus",
  "customerProfileStatus",
  "perspectiveCards",
  "renderPerspective",
  "demoGuide",
  "renderDemoGuide",
  "demoCueCards",
  "renderDemoCueCards",
  "copyDemoCue",
  "Copy Cue",
  "You should be able to see what is happening with your job",
  "demoPaths",
  "renderDemoPath",
  "renderDemoLinks",
  "customerDemoJobPriority",
  "Homeowner proof",
  "Forge Auto services proof",
  "Auto buyer / seller",
  "Forge Auto can capture vehicle service",
  "autoLeadRouteRows",
  "Soft launch route",
  "Forge Auto Services:",
  "renderDemoOutcomes",
  "renderNavigationState",
  "renderFinishChecklist",
  "copyDemoScript",
  "copyDemoPack",
  "copyDemoLink",
  "copyCloseAsk",
  "renderSafetyCenter",
  "renderSoftLaunchPlan",
  "softLaunchRows",
  "renderSoftLaunchInvites",
  "softLaunchInviteRows",
  "renderSoftLaunchRunSheet",
  "softLaunchRunSheetRows",
  "copySoftLaunchPlan",
  "copySoftLaunchInvite",
  "copySoftLaunchInviteKit",
  "copySoftLaunchRunSheet",
  "Forge soft launch tomorrow plan",
  "Forge soft launch invite kit",
  "Forge launch day run sheet",
  "Controlled soft launch only",
  "launchGateRows",
  "Ready for controlled signups",
  "Do not send broadly yet",
  "copyLaunchGate",
  "deployPreflightRows",
  "publicReadinessSummary",
  "publicReadinessBlockers",
  "Public beta readiness",
  "finalSecurityGate",
  "Static host security config",
  "Lead capture backend",
  "Client admin gate",
  "copyDeployPlan",
  "copyReleaseCandidatePacket",
  "Forge public beta release candidate packet",
  "copyLaunchRunbook",
  "Forge public beta deploy runbook",
  "copySecurityCommand",
  "npm run check",
  "copyFinalSecurityGate",
  "finalSecurityGateRows",
  "Forge final public gate",
  "copySecurityReviewPack",
  "Forge final public security review",
  "safetyChecks",
  "copySafetyChecklist",
  "lastBackupLeadCount",
  "renderLaunchCommandCenter",
  "launchCommandRows",
  "copyLaunchCommand",
  "renderOutreachRecap",
  "outreachRecapSummary",
  "copyOutreachRecap",
  "renderOutreachBatch",
  "outreachBatchRows",
  "copyOutreachBatch",
  "completeOutreachSprint",
  "Outreach sprint completed",
  "renderSessionHistory",
  "outreachSessionHistory",
  "copySessionHistory",
  "copySessionNote",
  "Selected bid handoff",
  "chosenBidHandoff",
  "bidHandoffText",
  "copyBidHandoff",
  "closeAskText",
  "roleDemoLink",
  "copyPerspectiveLink",
  "perspectiveLink",
  "copy-perspective-link",
  "demo=",
  "Bid chosen.",
  "View as"
];

const html = await readFile("index.html", "utf8");
const js = await readFile("app.js", "utf8");
const css = await readFile("styles.css", "utf8");
const manifest = await readFile("manifest.webmanifest", "utf8");
const serviceWorker = await readFile("service-worker.js", "utf8");
const netlify = await readFile("netlify.toml", "utf8");
const vercel = await readFile("vercel.json", "utf8");
const robots = await readFile("robots.txt", "utf8");
const securityReview = await readFile("SECURITY_REVIEW_CHECKLIST.md", "utf8");
const supabaseSchema = await readFile("SUPABASE_SCHEMA.sql", "utf8");
const webhookPayloads = await readFile("WEBHOOK_PAYLOADS.md", "utf8");
const adminAuthPlan = await readFile("ADMIN_AUTH_PLAN.md", "utf8");
const securityCheck = await readFile("security-check.mjs", "utf8");
const deployRunbook = await readFile("PUBLIC_BETA_DEPLOY_RUNBOOK.md", "utf8");
const releaseManifest = await readFile("release-manifest.json", "utf8");
const releaseCandidate = await readFile("RELEASE_CANDIDATE.md", "utf8");
const releaseCheck = await readFile("release-check.mjs", "utf8");
const packageJson = await readFile("package.json", "utf8");
const githubWorkflow = await readFile(".github/workflows/forge-checks.yml", "utf8");
const finalPublicGate = await readFile("FINAL_PUBLIC_GATE.md", "utf8");
const autoDealerIntegration = await readFile("AUTO_DEALER_INTEGRATION.md", "utf8");
const photographyRoute = await readFile("photography/index.html", "utf8");
const photographyRequestRoute = await readFile("photography/request/index.html", "utf8");
const photographyApplyRoute = await readFile("photography/apply/index.html", "utf8");
const creativeRoute = await readFile("photography-videography/index.html", "utf8");
const northstarRoute = await readFile("northstar-creative/index.html", "utf8");
const buildingRoute = await readFile("building/index.html", "utf8");
const adminBuildingRoute = await readFile("admin/building-leads/index.html", "utf8");
const forgeAcademyRoute = await readFile("forge-academy/index.html", "utf8");
const forgeAcademyApplyRoute = await readFile("forge-academy/apply/index.html", "utf8");
const forgeAcademyEmployersRoute = await readFile("forge-academy/employers/index.html", "utf8");
const forgeAcademySchoolsRoute = await readFile("forge-academy/schools/index.html", "utf8");
const forgeCareerDashboardRoute = await readFile("dashboard/career/index.html", "utf8");
const admitlyTradePathwaysRoute = await readFile("trade-pathways/index.html", "utf8");
const admitlyTradePathwaysApplyRoute = await readFile("trade-pathways/apply/index.html", "utf8");
const admitlyTradePathwaysDashboardRoute = await readFile("dashboard/trade-pathways/index.html", "utf8");
const adminForgeAcademyRoute = await readFile("admin/forge-academy/index.html", "utf8");
const adminTradePathwaysRoute = await readFile("admin/trade-pathways/index.html", "utf8");
const forgeCapitalRoute = await readFile("forge/capital/index.html", "utf8");
const forgeFlexRoute = await readFile("forge/flex/index.html", "utf8");
const partnersFlexRoute = await readFile("partners/flex/index.html", "utf8");
const personalDriverRoute = await readFile("personal-driver/index.html", "utf8");
const privateDriverRoute = await readFile("private-driver/index.html", "utf8");
const forgePaymentsRoute = await readFile("forge-payments/index.html", "utf8");
const merchantServicesRoute = await readFile("merchant-services/index.html", "utf8");
const localProductsRoute = await readFile("local-products/index.html", "utf8");
const makersRoute = await readFile("makers/index.html", "utf8");
const flexMigration = await readFile("migrations/20260626_forge_flex_leads.sql", "utf8");
const flexReadme = await readFile("docs/forge-capital-desk-readme.md", "utf8");
const flexOutreach = await readFile("docs/forge-flex-capital-desk-outreach.md", "utf8");
const admitlyTradePathwaysDoc = await readFile("docs/admitly-trade-pathways.md", "utf8");
const forgeAcademyDoc = await readFile("docs/forge-academy.md", "utf8");
const admitlyForgeBridgeDoc = await readFile("docs/admitly-forge-career-bridge.md", "utf8");
const forgeCareerPlusDoc = await readFile("docs/forge-career-plus.md", "utf8");
const flexApiRoute = await readFile("api/forge/flex-leads/route.ts", "utf8");
const envExample = await readFile(".env.example", "utf8");
const requiredTradeLabels = [
  "Electrician",
  "Plumbing",
  "HVAC",
  "Roofing",
  "Carpentry",
  "Welding",
  "Concrete",
  "Masonry",
  "Heavy Equipment",
  "CDL Training",
  "Diesel Mechanics",
  "Automotive",
  "Landscaping",
  "Arborist",
  "Solar Installation",
  "Fiber Optics",
  "Low Voltage Systems",
  "Appliance Repair",
  "Painting",
  "General Contracting"
];
const missingTradeLabels = requiredTradeLabels.filter((label) => !js.includes(`label: "${label}"`) && !js.includes(`category: "${label}"`) && !js.includes(`categoryLabel: "${label}"`));
const missingTradeHooks = [
  ["customer job category", html.includes("id=\"jobCategory\"")],
  ["service job details", html.includes("id=\"serviceJobFields\"")],
  ["provider vertical", html.includes("id=\"workerServiceVertical\"")],
  ["provider trade categories", html.includes("id=\"workerTradeCategories\"")],
  ["provider profile fields", html.includes("id=\"providerProfileFields\"")],
  ["job board category filter", html.includes("id=\"listingCategory\"")],
  ["provider directory filter", html.includes("id=\"providerVerticalFilter\"")],
  ["admin category filter", html.includes("id=\"adminTradeCategoryFilter\"")],
  ["homepage trade grid", html.includes("id=\"requiredTradeCategoryGrid\"")],
  ["central trade schema", js.includes("forgeTradeCategorySchema")]
].filter(([, ok]) => !ok).map(([label]) => label);

const missingHtml = requiredHtml.filter((text) => !html.includes(text));
const missingJs = requiredJs.filter((text) => !js.includes(text));
const missingCss = [
  ["safe-area mobile tabbar", css.includes("env(safe-area-inset-bottom)")],
  ["compact phone feature strip", css.includes(".feature-strip") && css.includes("repeat(3, minmax(0, 1fr))")],
  ["auto services", css.includes(".auto-layout") && css.includes(".auto-card") && css.includes(".auto-sell-card") && css.includes(".auto-service-grid")],
  ["auto transport and platinum", css.includes(".auto-transport-grid") && css.includes(".forge-platinum-panel")],
  ["auto admin operations", css.includes(".auto-admin-ops") && css.includes(".auto-admin-columns") && css.includes(".operations-vault-grid")],
  ["auto service requests", css.includes(".auto-request-section") && css.includes(".auto-request-list") && css.includes(".auto-service-form")],
  ["auto dealer network", css.includes(".auto-dealer-grid") && css.includes(".auto-dealers")],
  ["auto dealer setup", css.includes(".auto-setup-grid") && css.includes(".auto-setup")],
  ["auto buyer inquiries", css.includes(".auto-inquiries") && css.includes(".auto-inquiry-list")],
  ["auto lead route", css.includes(".auto-route-grid") && css.includes(".auto-route")],
  ["photography videography page", css.includes(".creative-layout") && css.includes(".creative-service-grid") && css.includes(".creative-provider-panel")],
  ["photography quality notes", css.includes(".creative-quality") && css.includes(".creative-booking-notes") && css.includes(".creative-disclaimer")],
  ["northstar creative page", css.includes(".northstar-layout") && css.includes(".northstar-package-grid") && css.includes(".northstar-intake-panel")],
  ["northstar lead cards", css.includes(".northstar-chip-grid") && css.includes(".northstar-lead-list")],
  ["building page", css.includes(".building-hero") && css.includes(".building-intake-card") && css.includes(".building-card-grid")],
  ["capital desk page", css.includes(".capital-layout") && css.includes(".capital-hero") && css.includes(".capital-form-panel")],
  ["flex admin and status", css.includes(".flex-status") && css.includes(".flex-admin-section") && css.includes(".flex-filter-row")],
  ["provider growth tools", css.includes(".provider-growth-tools")],
  ["homebuilding page", css.includes(".homebuilding-layout") && css.includes(".tracker-feature-card")],
  ["build tracker dashboard", css.includes(".build-tracker-dashboard") && css.includes(".tracker-card")],
  ["build tracker gantt", css.includes(".gantt-scroll") && css.includes(".gantt-bar")],
  ["build tracker budget", css.includes(".budget-category-grid") && css.includes(".budget-alerts")],
  ["training careers hub", css.includes(".opportunity-layout") && css.includes(".opportunity-track-grid") && css.includes(".opportunity-lead-list")],
  ["forge academy and admitly pages", css.includes(".academy-layout") && css.includes(".academy-option-grid") && css.includes(".admitly-layout") && css.includes(".admitly-path-grid")],
  ["academy admin grids", css.includes(".academy-admin-stats") && css.includes(".academy-partner-grid")],
  ["soft launch plan", css.includes(".soft-launch-grid") && css.includes(".soft-launch")],
  ["first user start path", css.includes(".start-path-grid") && css.includes(".start-path-card")],
  ["first user path heading", css.includes(".start-path-heading")],
  ["signup readiness panel", css.includes(".signup-readiness-panel") && css.includes(".readiness-grid")],
  ["launch gate panel", css.includes(".launch-gate") && css.includes(".launch-gate-card.blocked")],
  ["deploy preflight panel", css.includes(".deploy-preflight") && css.includes(".deploy-grid")],
  ["readiness score panel", css.includes(".readiness-score") && css.includes(".readiness-score h3")],
  ["profile brief panel", css.includes(".profile-brief-grid") && css.includes(".profile-brief-heading")],
  ["final gate panel", css.includes(".final-gate") && css.includes(".final-gate article.hold")],
  ["delivery status panel", css.includes(".delivery-status") && css.includes(".delivery-grid")],
  ["backend handoff panel", css.includes(".backend-handoff") && css.includes(".backend-grid")],
  ["auth handoff panel", css.includes(".auth-handoff") && css.includes(".auth-grid")],
  ["legal screen", css.includes(".legal-layout") && css.includes(".legal-grid")],
  ["confirmation next steps", css.includes(".confirm-next") && css.includes(".confirm-next article")],
  ["confirmation handoff", css.includes(".confirm-handoff") && css.includes("border-left: 6px solid var(--orange)")],
  ["job flow tracker", css.includes(".job-flow-grid") && css.includes(".job-flow-grid article.active")],
  ["job flow brief", css.includes(".job-flow-brief-grid") && css.includes(".job-flow-brief-heading")],
  ["status empty guidance", css.includes(".status-empty")],
  ["admin safety grid", css.includes(".safety-grid") && css.includes(".safety-item.attention")],
  ["launch command cards", css.includes(".launch-command-grid") && css.includes(".command-meter")],
  ["outreach recap grid", css.includes(".outreach-recap-grid") && css.includes(".recap-list")],
  ["next 10 outreach batch", css.includes(".next-batch-list") && css.includes(".batch-row")],
  ["compact action buttons", css.includes(".compact-actions")],
  ["session history cards", css.includes(".session-history-list") && css.includes(".session-card")],
  ["selected bid handoff card", css.includes(".handoff-card") && css.includes(".handoff-grid")]
].filter(([, ok]) => !ok).map(([label]) => label);
const missingPwa = [
  ["manifest link", html.includes("manifest.webmanifest")],
  ["service worker registration", js.includes("registerServiceWorker")],
  ["manifest name", manifest.includes("Forge MVP")],
  ["service worker cache", serviceWorker.includes("CACHE_NAME")],
  ["fresh service worker cache", serviceWorker.includes("forge-mvp-v71")]
].filter(([, ok]) => !ok).map(([label]) => label);
const missingDeploy = [
  ["netlify security headers", netlify.includes("Content-Security-Policy") && netlify.includes("X-Frame-Options")],
  ["netlify spa redirect", netlify.includes("[[redirects]]") && netlify.includes("/index.html")],
  ["vercel security headers", vercel.includes("Content-Security-Policy") && vercel.includes("Permissions-Policy")],
  ["vercel rewrite", vercel.includes("\"rewrites\"") && vercel.includes("\"/index.html\"")],
  ["robots present", robots.includes("User-agent: *")],
  ["security review checklist", securityReview.includes("Forge Security Review Checklist") && securityReview.includes("Launch Decision")],
  ["supabase schema", supabaseSchema.includes("forge_job_leads") && supabaseSchema.includes("forge_opportunity_leads") && supabaseSchema.includes("trade_pathway_leads") && supabaseSchema.includes("forge_academy_leads") && supabaseSchema.includes("forge_career_profiles") && supabaseSchema.includes("school_partners") && supabaseSchema.includes("employer_training_partners") && supabaseSchema.includes("resume_requests") && supabaseSchema.includes("photography_videography") && supabaseSchema.includes("creative_service_requests") && supabaseSchema.includes("creative_provider_applications") && supabaseSchema.includes("northstar_marketing_operations_leads") && supabaseSchema.includes("forge_flex_leads") && supabaseSchema.includes("personal_driver_requests") && supabaseSchema.includes("personal_driver_provider_applications") && supabaseSchema.includes("forge_merchant_service_leads") && supabaseSchema.includes("local_product_vendor_leads") && supabaseSchema.includes("worker_trust_proof_ledger") && supabaseSchema.includes("building_leads") && supabaseSchema.includes("forge_vehicle_seller_leads") && supabaseSchema.includes("forge_operations_vault_documents") && supabaseSchema.includes("enable row level security")],
  ["webhook payload docs", webhookPayloads.includes("Forge Webhook Payloads") && webhookPayloads.includes("photography_videography") && webhookPayloads.includes("northstar") && webhookPayloads.includes("forge-flex") && webhookPayloads.includes("personal-driver-request") && webhookPayloads.includes("forge-merchant-services") && webhookPayloads.includes("local-product-vendor") && webhookPayloads.includes("vehicle-seller") && webhookPayloads.includes("forge-academy") && webhookPayloads.includes("trade-pathway") && webhookPayloads.includes("employer-training-partner") && webhookPayloads.includes("school-program-partner") && webhookPayloads.includes("resume-request") && webhookPayloads.includes("Public Beta Safety")],
  ["admin auth plan", adminAuthPlan.includes("Forge Admin Auth Plan") && adminAuthPlan.includes("Minimum Public Beta Rule")],
  ["security check script", securityCheck.includes("Forge security check passed.") && securityCheck.includes("fresh cache version")],
  ["public beta deploy runbook", deployRunbook.includes("Forge Public Beta Deploy Runbook") && deployRunbook.includes("Stop Conditions")],
  ["release manifest", releaseManifest.includes("Forge Public Beta Release Candidate") && releaseManifest.includes("\"version\": \"v71\"") && releaseManifest.includes("/photography?v=71") && releaseManifest.includes("/photography/request?v=71") && releaseManifest.includes("/photography/apply?v=71") && releaseManifest.includes("/photography-videography?v=71") && releaseManifest.includes("/northstar-creative?v=71") && releaseManifest.includes("/forge/capital?v=71") && releaseManifest.includes("/forge/flex?v=71") && releaseManifest.includes("/partners/flex?v=71") && releaseManifest.includes("/personal-driver?v=71") && releaseManifest.includes("/forge-payments?v=71") && releaseManifest.includes("/local-products?v=71") && releaseManifest.includes("/building?v=71") && releaseManifest.includes("/admin/building-leads?v=71") && releaseManifest.includes("/forge-academy?v=71") && releaseManifest.includes("/trade-pathways?v=71") && releaseManifest.includes("/admin/forge-academy?v=71")],
  ["capital desk cached routes", serviceWorker.includes("./forge/capital/") && serviceWorker.includes("./forge/flex/") && serviceWorker.includes("./partners/flex/")],
  ["new lane cached routes", serviceWorker.includes("./personal-driver/") && serviceWorker.includes("./private-driver/") && serviceWorker.includes("./forge-payments/") && serviceWorker.includes("./merchant-services/") && serviceWorker.includes("./local-products/") && serviceWorker.includes("./makers/")],
  ["building cached routes", serviceWorker.includes("./building/") && serviceWorker.includes("./admin/building-leads/")],
  ["academy cached routes", serviceWorker.includes("./forge-academy/") && serviceWorker.includes("./trade-pathways/") && serviceWorker.includes("./admin/forge-academy/")],
  ["academy route aliases", forgeAcademyRoute.includes("route-loader.js") && forgeAcademyApplyRoute.includes("route-loader.js") && forgeAcademyEmployersRoute.includes("route-loader.js") && forgeAcademySchoolsRoute.includes("route-loader.js") && forgeCareerDashboardRoute.includes("route-loader.js")],
  ["admitly route aliases", admitlyTradePathwaysRoute.includes("route-loader.js") && admitlyTradePathwaysApplyRoute.includes("route-loader.js") && admitlyTradePathwaysDashboardRoute.includes("route-loader.js") && adminForgeAcademyRoute.includes("route-loader.js") && adminTradePathwaysRoute.includes("route-loader.js")],
  ["academy docs", admitlyTradePathwaysDoc.includes("Admitly Trade Pathways") && forgeAcademyDoc.includes("Forge Academy") && admitlyForgeBridgeDoc.includes("Brand Separation") && forgeCareerPlusDoc.includes("Forge Career+")],
  ["release candidate notes", releaseCandidate.includes("Forge Public Beta Release Candidate") && releaseCandidate.includes("Human Gates Still Required")],
  ["release check script", releaseCheck.includes("Forge release check passed.") && releaseCheck.includes("service worker version")],
  ["package scripts", packageJson.includes("\"check\"") && packageJson.includes("check:release")],
  ["github checks workflow", githubWorkflow.includes("Forge Checks") && githubWorkflow.includes("npm run check")],
  ["final public gate", finalPublicGate.includes("Forge Final Public Gate") && finalPublicGate.includes("Launch Decision")],
  ["auto dealer integration", autoDealerIntegration.includes("Forge Auto Dealer Integration") && autoDealerIntegration.includes("JoCo Auto Sales")],
  ["photography route", photographyRoute.includes("Forge Photography & Videography") && photographyRoute.includes("/route-loader.js")],
  ["photography request route", photographyRequestRoute.includes("Forge Photography & Videography Request") && photographyRequestRoute.includes("/route-loader.js")],
  ["photography apply route", photographyApplyRoute.includes("Forge Photography & Videography Provider Application") && photographyApplyRoute.includes("/route-loader.js")],
  ["photography videography alias route", creativeRoute.includes("Forge Photography & Videography") && creativeRoute.includes("/route-loader.js")],
  ["northstar creative route", northstarRoute.includes("Forge NorthStar Creative Co.") && northstarRoute.includes("/route-loader.js")],
  ["forge capital route", forgeCapitalRoute.includes("Forge Capital Desk") && forgeCapitalRoute.includes("/route-loader.js")],
  ["forge flex route", forgeFlexRoute.includes("Forge Flex Referral") && forgeFlexRoute.includes("/route-loader.js")],
  ["partners flex route", partnersFlexRoute.includes("Forge Partner: Flex") && partnersFlexRoute.includes("/route-loader.js")],
  ["personal driver route", personalDriverRoute.includes("Forge Personal Driver") && personalDriverRoute.includes("/route-loader.js")],
  ["private driver route", privateDriverRoute.includes("Forge Private Driver") && privateDriverRoute.includes("/route-loader.js")],
  ["forge payments route", forgePaymentsRoute.includes("Forge Payments") && forgePaymentsRoute.includes("/route-loader.js")],
  ["merchant services route", merchantServicesRoute.includes("Forge Merchant Services") && merchantServicesRoute.includes("/route-loader.js")],
  ["local products route", localProductsRoute.includes("Forge Local Products") && localProductsRoute.includes("/route-loader.js")],
  ["makers route", makersRoute.includes("Forge Makers") && makersRoute.includes("/route-loader.js")],
  ["building route", buildingRoute.includes("Forge Building") && buildingRoute.includes("/route-loader.js")],
  ["admin building route", adminBuildingRoute.includes("Forge Building Leads Admin") && adminBuildingRoute.includes("/route-loader.js")],
  ["flex lead migration", flexMigration.includes("public.forge_flex_leads") && flexMigration.includes("interested_in_forge_job_leads") && flexMigration.includes("interested_in_website_crm_automation") && flexMigration.includes("consent_to_receive_flex_referral") && flexMigration.includes("status in")],
  ["flex docs", flexReadme.includes("Forge Capital Desk") && flexReadme.includes("NEXT_PUBLIC_FLEX_REFERRAL_URL") && flexOutreach.includes("Forge Capital Desk") && flexOutreach.includes("Compliance")],
  ["flex api route", flexApiRoute.includes("FORGE_GHL_WEBHOOK_URL") && flexApiRoute.includes("FORGE_ZAPIER_WEBHOOK_URL") && flexApiRoute.includes("forbiddenFieldPattern")],
  ["flex env example", envExample.includes("NEXT_PUBLIC_FLEX_REFERRAL_URL") && envExample.includes("https://REPLACE-WITH-OFFICIAL-FLEX-PARTNER-LINK") && envExample.includes("FLEX_APP_URL") && envExample.includes("FLEX_PARTNER_MODE") && envExample.includes("FORGE_CAPITAL_DESK_ENABLED")]
].filter(([, ok]) => !ok).map(([label]) => label);
const darkThemeLeak = /#09090b|color-scheme:\s*dark|industrial/i.test(css);

if (missingHtml.length || missingJs.length || missingCss.length || missingPwa.length || missingDeploy.length || missingTradeLabels.length || missingTradeHooks.length || darkThemeLeak) {
  console.error("Forge smoke test failed.");
  if (missingHtml.length) console.error("Missing HTML:", missingHtml.join(", "));
  if (missingJs.length) console.error("Missing JS:", missingJs.join(", "));
  if (missingCss.length) console.error("Missing CSS:", missingCss.join(", "));
  if (missingPwa.length) console.error("Missing PWA:", missingPwa.join(", "));
  if (missingDeploy.length) console.error("Missing Deploy:", missingDeploy.join(", "));
  if (missingTradeLabels.length) console.error("Missing trade categories:", missingTradeLabels.join(", "));
  if (missingTradeHooks.length) console.error("Missing trade hooks:", missingTradeHooks.join(", "));
  if (darkThemeLeak) console.error("Found a dark-theme marker in styles.css");
  process.exit(1);
}

console.log("Forge smoke test passed.");
