export const monetizationVersion = "monetization_scale_v1";

export const planTiers = [
  {
    id: "forge_free",
    app: "forge",
    name: "Forge Free",
    slug: "forge-free",
    billingInterval: "monthly",
    monthlyPriceCents: 0,
    annualPriceCents: 0,
    description: "Useful public profile and customer/job posting access with organic discovery.",
    features: ["Basic worker/business profile", "Basic customer job posting", "Limited job replies/bids per month", "Basic categories and service area", "Organic search only", "Basic review collection"],
    limits: { monthlyBids: 5, photos: 3, serviceAreas: 1, teamSeats: 1 },
    rankingMultiplier: 1,
    boostCreditsPerMonth: 0,
    verificationIncluded: false,
    analyticsIncluded: false,
    profileEnhancementIncluded: false,
    supportLevel: "standard",
    active: true,
    sortOrder: 10,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "forge_verified",
    app: "forge",
    name: "Forge Verified",
    slug: "forge-verified",
    billingInterval: "monthly",
    monthlyPriceCents: 2900,
    annualPriceCents: 29900,
    description: "Verification review workflow, better profile card, one boost credit, and basic analytics after trust gates pass.",
    features: ["Identity/business/license/insurance review where applicable", "Verified badge only after approval", "More photos/portfolio items", "1 monthly profile boost credit", "Profile views, quote clicks, contact clicks", "Fast response badge eligibility"],
    limits: { monthlyBids: 25, photos: 12, serviceAreas: 2, teamSeats: 1 },
    rankingMultiplier: 1.08,
    boostCreditsPerMonth: 1,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "standard-plus",
    active: true,
    sortOrder: 20,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "forge_plus",
    app: "forge",
    name: "Forge Plus",
    slug: "forge-plus",
    billingInterval: "monthly",
    monthlyPriceCents: 9900,
    annualPriceCents: 99900,
    description: "Priority category placement after compliance gates, enhanced profile tools, lead alerts, quote templates, and CRM/export-ready lead table.",
    features: ["Everything in Verified", "4 monthly boost credits", "Video/project gallery/service packages", "Lead alerts", "Quote templates", "Saved bids", "Profile completeness coach", "Review request tools", "Promoted slots when boosted"],
    limits: { monthlyBids: 100, photos: 40, serviceAreas: 4, teamSeats: 3 },
    rankingMultiplier: 1.16,
    boostCreditsPerMonth: 4,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "priority",
    active: true,
    sortOrder: 30,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "forge_pro_max",
    app: "forge",
    name: "Forge Pro Max",
    slug: "forge-pro-max",
    billingInterval: "monthly",
    monthlyPriceCents: 24900,
    annualPriceCents: 249900,
    description: "Crew/team features, multiple service areas, pipeline dashboard, advanced analytics, and higher sponsored placement caps.",
    features: ["Everything in Plus", "12 monthly boost credits", "Team/crew profiles", "Multiple service areas", "Job pipeline dashboard", "Priority bid visibility", "Advanced analytics", "Automated follow-up templates", "Managed crew eligibility"],
    limits: { monthlyBids: 300, photos: 120, serviceAreas: 12, teamSeats: 10 },
    rankingMultiplier: 1.24,
    boostCreditsPerMonth: 12,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "priority-plus",
    active: true,
    sortOrder: 40,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "forge_elite_company",
    app: "forge",
    name: "Forge Elite Company",
    slug: "forge-elite-company",
    billingInterval: "monthly",
    monthlyPriceCents: 49900,
    annualPriceCents: 499900,
    description: "Multi-user company account, company verification vault, premium sponsored inventory, white-glove profile buildout queue, and enterprise reporting.",
    features: ["Everything in Pro Max", "Multiple workers under one company", "Company verification vault", "Insurance/license expiration reminders", "Dedicated category landing page", "North Star Creative Co. upsell area", "Enterprise reporting", "Priority support"],
    limits: { monthlyBids: 1000, photos: 300, serviceAreas: 50, teamSeats: 50 },
    rankingMultiplier: 1.32,
    boostCreditsPerMonth: 20,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "enterprise",
    active: true,
    sortOrder: 50,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "stitch_licensed_basic_v2",
    app: "stitch",
    name: "Stitch Licensed Basic",
    slug: "stitch-licensed-basic",
    billingInterval: "monthly",
    monthlyPriceCents: 0,
    annualPriceCents: 0,
    description: "Verified entry-level access for licensed cannabis operators. License verification required before transacting.",
    features: ["License verification required", "Basic company profile", "Limited listings/SKUs", "Basic COA upload area", "Basic buyer/supplier matching", "Organic search only"],
    limits: { listings: 10, campaigns: 0, teamSeats: 1 },
    rankingMultiplier: 1,
    boostCreditsPerMonth: 0,
    verificationIncluded: true,
    analyticsIncluded: false,
    profileEnhancementIncluded: false,
    supportLevel: "standard",
    transactionFeeTargetBps: 1500,
    active: true,
    sortOrder: 10,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "stitch_bronze_visibility_v2",
    app: "stitch",
    name: "Stitch Bronze Visibility",
    slug: "stitch-bronze-visibility",
    billingInterval: "monthly",
    monthlyPriceCents: 9900,
    annualPriceCents: 100000,
    description: "Better verified company card, more listings, basic analytics, one monthly boost, and sponsored placement eligibility after compliance gates.",
    features: ["Verified business profile after approval", "Better company card", "More listings/SKUs", "Basic analytics", "1 monthly boost", "Buyer inquiry tools", "Sponsored placement eligible"],
    limits: { listings: 50, campaigns: 1, teamSeats: 2 },
    rankingMultiplier: 1.08,
    boostCreditsPerMonth: 1,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "standard-plus",
    transactionFeeTargetBps: 1500,
    active: true,
    sortOrder: 20,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "stitch_silver_growth_v2",
    app: "stitch",
    name: "Stitch Silver Growth",
    slug: "stitch-silver-growth",
    billingInterval: "monthly",
    monthlyPriceCents: 49900,
    annualPriceCents: 500000,
    description: "Deal tools, buyer analytics, four boosts, and category ranking boost after license/COA/admin gates.",
    features: ["Everything in Bronze", "4 monthly boost credits", "Buyer interest analytics", "Preferred pricing/deal tools", "Deal drop campaigns", "More listings/SKUs", "Compliance-gated category boost"],
    limits: { listings: 250, campaigns: 4, teamSeats: 5 },
    rankingMultiplier: 1.16,
    boostCreditsPerMonth: 4,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "priority",
    transactionFeeTargetBps: 800,
    active: true,
    sortOrder: 30,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "stitch_gold_marketplace_v2",
    app: "stitch",
    name: "Stitch Gold Marketplace",
    slug: "stitch-gold-marketplace",
    billingInterval: "monthly",
    monthlyPriceCents: 250000,
    annualPriceCents: 2500000,
    description: "Top category promoted slots where available, buyer segment campaigns, vault enhancements, workflow tools, and advanced analytics.",
    features: ["Everything in Silver", "Top promoted slots where available", "Product/menu campaign tools", "Buyer segment campaigns", "COA/lab document vault enhancements", "Order workflow readiness", "Priority support"],
    limits: { listings: 1000, campaigns: 12, teamSeats: 12 },
    rankingMultiplier: 1.24,
    boostCreditsPerMonth: 12,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "priority-plus",
    transactionFeeTargetBps: 600,
    active: true,
    sortOrder: 40,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "stitch_platinum_state_leader_v2",
    app: "stitch",
    name: "Stitch Platinum State Leader",
    slug: "stitch-platinum-state-leader",
    billingInterval: "monthly",
    monthlyPriceCents: 500000,
    annualPriceCents: 5000000,
    description: "State/category leadership placement where legally available, logistics concierge workflow, team seats, multi-location support, and state-specific campaign pages.",
    features: ["Everything in Gold", "State/category leadership placement", "Priority qualified buyer introductions", "Logistics/fulfillment concierge workflow", "Team seats", "Multi-location support", "State-specific campaign pages"],
    limits: { listings: 3000, campaigns: 30, teamSeats: 30 },
    rankingMultiplier: 1.3,
    boostCreditsPerMonth: 24,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "enterprise",
    transactionFeeTargetBps: 300,
    active: true,
    sortOrder: 50,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "stitch_diamond_enterprise_v2",
    app: "stitch",
    name: "Stitch Diamond Enterprise",
    slug: "stitch-diamond-enterprise",
    billingInterval: "monthly",
    monthlyPriceCents: 1000000,
    annualPriceCents: 10000000,
    description: "Invite-only enterprise profile, legal multi-state expansion workspace, custom reports, white-label pages, priority onboarding, analytics, and data room.",
    features: ["Everything in Platinum", "Invite-only enterprise profile", "Multi-state workspace only where legal", "Custom reports", "White-label landing pages", "Priority onboarding", "Enterprise analytics", "Compliance vault"],
    limits: { listings: 10000, campaigns: 100, teamSeats: 100 },
    rankingMultiplier: 1.36,
    boostCreditsPerMonth: 50,
    verificationIncluded: true,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "enterprise-plus",
    transactionFeeTargetBps: 190,
    active: true,
    sortOrder: 60,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "admitly_free",
    app: "admitly",
    name: "Admitly Free",
    slug: "admitly-free",
    billingInterval: "monthly",
    monthlyPriceCents: 0,
    annualPriceCents: 0,
    description: "Basic student profile, college/trade checklist, limited AI guidance, deadline tracker, and profile starter.",
    features: ["Basic student profile", "Basic college/trade pathway checklist", "Limited AI guidance messages", "Basic deadline tracker", "Basic school/trade/apprenticeship search", "Basic resume/profile starter"],
    limits: { aiMessages: 10, students: 1, schoolList: 8 },
    rankingMultiplier: 1,
    boostCreditsPerMonth: 0,
    verificationIncluded: false,
    analyticsIncluded: false,
    profileEnhancementIncluded: false,
    supportLevel: "standard",
    active: true,
    sortOrder: 10,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "admitly_starter",
    app: "admitly",
    name: "Admitly Starter",
    slug: "admitly-starter",
    billingInterval: "monthly",
    monthlyPriceCents: 900,
    annualPriceCents: 9900,
    description: "More AI guidance, personalized roadmap, deadline calendar, tracker, essay outline helper, and pathway checklist.",
    features: ["More AI guidance", "Personalized roadmap", "Deadline calendar", "GPA/test/extracurricular tracker", "Basic essay outline helper", "Scholarship search basics", "Trade/apprenticeship checklist"],
    limits: { aiMessages: 100, students: 1, schoolList: 25 },
    rankingMultiplier: 1,
    boostCreditsPerMonth: 0,
    verificationIncluded: false,
    analyticsIncluded: false,
    profileEnhancementIncluded: true,
    supportLevel: "standard-plus",
    active: true,
    sortOrder: 20,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "admitly_plus",
    app: "admitly",
    name: "Admitly Plus",
    slug: "admitly-plus",
    billingInterval: "monthly",
    monthlyPriceCents: 2900,
    annualPriceCents: 29900,
    description: "AI counselor, essay review assistant, resume builder, parent view, reminders, school list, scholarship matching, and Forge-ready blue-collar export.",
    features: ["Everything in Starter", "AI counselor", "Essay draft review assistant", "Resume builder", "Parent view", "Smart reminders", "School list builder", "Application progress score", "Scholarship matching", "Forge-ready resume/profile export"],
    limits: { aiMessages: 500, students: 1, schoolList: 75 },
    rankingMultiplier: 1,
    boostCreditsPerMonth: 0,
    verificationIncluded: false,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "priority",
    active: true,
    sortOrder: 30,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "admitly_pro",
    app: "admitly",
    name: "Admitly Pro",
    slug: "admitly-pro",
    billingInterval: "monthly",
    monthlyPriceCents: 9900,
    annualPriceCents: 99900,
    description: "Priority AI review, essay versioning, interview prep, collaboration workspace, reports, career/trade matching, templates, and package export.",
    features: ["Everything in Plus", "Priority AI review queue", "Advanced essay versioning", "Interview prep", "Counselor/tutor workspace", "Advanced school fit reports", "Career/trade/union matching", "Premium templates", "Application package export"],
    limits: { aiMessages: 2000, students: 1, schoolList: 200 },
    rankingMultiplier: 1,
    boostCreditsPerMonth: 0,
    verificationIncluded: false,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "priority-plus",
    active: true,
    sortOrder: 40,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "admitly_family_premium",
    app: "admitly",
    name: "Admitly Family Premium",
    slug: "admitly-family-premium",
    billingInterval: "package",
    monthlyPriceCents: 49900,
    annualPriceCents: 0,
    description: "Multi-student family dashboard, parent strategy dashboard, essay package workflow, sprint planner, and manual human-review placeholder.",
    features: ["Everything in Pro", "Multi-student family dashboard", "Parent strategy dashboard", "Premium essay workflow", "Application sprint planner", "Counselor/tutor review queue placeholder", "No admissions guarantee"],
    limits: { aiMessages: 5000, students: 4, schoolList: 500 },
    rankingMultiplier: 1,
    boostCreditsPerMonth: 0,
    verificationIncluded: false,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "concierge-manual",
    active: true,
    sortOrder: 50,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  },
  {
    id: "admitly_elite_concierge",
    app: "admitly",
    name: "Admitly Elite Concierge",
    slug: "admitly-elite-concierge",
    billingInterval: "package",
    monthlyPriceCents: 499900,
    annualPriceCents: 0,
    description: "Invite-only white-glove planning package. Purchase remains manually approved and capacity-gated.",
    features: ["Invite-only/application-only", "White-glove college/trade pathway planning", "Full application calendar", "Essay strategy package", "Scholarship organization", "Parent/student meetings workflow placeholder", "Manual service tracker", "No admissions guarantee"],
    limits: { aiMessages: 10000, students: 2, schoolList: 1000 },
    rankingMultiplier: 1,
    boostCreditsPerMonth: 0,
    verificationIncluded: false,
    analyticsIncluded: true,
    profileEnhancementIncluded: true,
    supportLevel: "elite-manual",
    active: false,
    sortOrder: 60,
    createdAt: "2026-06-27",
    updatedAt: "2026-06-27"
  }
];

export const addOns = [
  { id: "forge_local_boost_30m", app: "forge", name: "30-minute local boost", slug: "forge-local-boost-30m", priceCents: 900, type: "boost", durationMinutes: 30, quantity: 1, active: true, termsDisclaimer: "Promoted placement only after trust and safety gates. No guaranteed jobs." },
  { id: "forge_category_boost_24h", app: "forge", name: "24-hour category boost", slug: "forge-category-boost-24h", priceCents: 2900, type: "boost", durationDays: 1, quantity: 1, active: true, termsDisclaimer: "Promoted placement must be labeled. No guaranteed leads." },
  { id: "forge_city_category_boost_7d", app: "forge", name: "7-day city/category boost", slug: "forge-city-category-boost-7d", priceCents: 9900, type: "boost", durationDays: 7, quantity: 1, active: true, termsDisclaimer: "Paid rank cannot override safety, license, or compliance penalties." },
  { id: "forge_super_bid", app: "forge", name: "Super Bid / Priority Quote", slug: "forge-super-bid", priceCents: 500, type: "super_bid", quantity: 1, active: true, termsDisclaimer: "Priority quote visibility does not guarantee selection." },
  { id: "forge_verification_basic", app: "forge", name: "Basic verification review", slug: "forge-verification-basic", priceCents: 4900, type: "verification_review", quantity: 1, active: true, termsDisclaimer: "Review fee does not guarantee approval or a badge." },
  { id: "forge_profile_buildout_starter", app: "forge", name: "North Star starter profile buildout", slug: "forge-profile-buildout-starter", priceCents: 19900, type: "profile_buildout", quantity: 1, active: true, termsDisclaimer: "Marketing support does not guarantee jobs or rankings." },
  { id: "stitch_listing_boost_24h", app: "stitch", name: "24-hour product/listing boost", slug: "stitch-listing-boost-24h", priceCents: 9900, type: "boost", durationDays: 1, quantity: 1, active: true, termsDisclaimer: "License, COA, METRC, state rules, and admin approval override paid placement." },
  { id: "stitch_state_spotlight_7d", app: "stitch", name: "7-day state/category spotlight", slug: "stitch-state-spotlight-7d", priceCents: 50000, type: "featured_listing", durationDays: 7, quantity: 1, active: true, termsDisclaimer: "Manual/admin gated. No interstate or noncompliant transactions." },
  { id: "stitch_buyer_blast", app: "stitch", name: "Buyer Blast", slug: "stitch-buyer-blast", priceCents: 25000, type: "buyer_blast", quantity: 1, active: true, termsDisclaimer: "Only to opted-in licensed buyer segments. No guarantee of orders." },
  { id: "stitch_coa_review", app: "stitch", name: "COA/lab verification review per SKU", slug: "stitch-coa-review", priceCents: 7500, type: "verification_review", quantity: 1, active: true, termsDisclaimer: "Review fee does not guarantee approval." },
  { id: "admitly_essay_ai_pack", app: "admitly", name: "Essay review AI pack", slug: "admitly-essay-ai-pack", priceCents: 1900, type: "essay_review", quantity: 1, active: true, termsDisclaimer: "AI guidance only. No admission guarantee." },
  { id: "admitly_resume_polish", app: "admitly", name: "Resume/profile polish", slug: "admitly-resume-polish", priceCents: 2900, type: "profile_buildout", quantity: 1, active: true, termsDisclaimer: "No guarantee of admission, scholarship, job, or acceptance." },
  { id: "admitly_scholarship_sprint", app: "admitly", name: "Scholarship sprint pack", slug: "admitly-scholarship-sprint", priceCents: 4900, type: "essay_review", quantity: 1, active: true, termsDisclaimer: "Organization support only. No scholarship or aid guarantee." },
  { id: "admitly_deadline_concierge", app: "admitly", name: "Deadline concierge", slug: "admitly-deadline-concierge", priceCents: 9900, type: "concierge", quantity: 1, active: true, termsDisclaimer: "Manual capacity-gated support. No outcome guarantee." }
];

export const appDisclaimers = {
  forge: "Forge paid tiers improve tools, visibility, analytics, and profile quality. They do not guarantee jobs, leads, bids, licenses, or results. Verification badges show only after real approval.",
  stitch: "Stitch paid visibility is compliance-first. License verification, COA status, METRC/state rules, and admin approval override paid placement. Payment processing remains manual/admin-gated until cannabis payment compliance is approved.",
  admitly: "Admitly provides AI guidance and application support. It does not guarantee admission, scholarships, financial aid, jobs, apprenticeships, union acceptance, or school acceptance. Minor student visibility must remain private and consent-aware."
};

export function plansForApp(app) {
  return planTiers.filter((plan) => plan.app === app && plan.active).sort((a, b) => a.sortOrder - b.sortOrder);
}

export function addOnsForApp(app) {
  return addOns.filter((item) => item.app === app && item.active);
}

export function formatPrice(cents) {
  if (!cents) return "$0";
  return `$${(cents / 100).toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
}
